### ISSUE TITLE
List of all installed Plugins

### ISSUE THREAD

**Issue by orkenstein** [supermarin/Alcatraz#110]
I wonder how can I see list of ALL installed plugins? It may be quite annoying when u try to find concrete installed plugin from at the whole list.

**Comment by supermarin** [comment]
@werediver it's already implemented in `master`

**Comment by orkenstein** [comment]
Thanks, everybody!

**Comment by wfalkwallace** [comment]
is this filter visible yet? I dont see it :crying_cat_face:

**Comment by supermarin** [comment]
@wfalkwallace have you built from `master` ?

**Comment by wfalkwallace** [comment]
no - I guess I need to for this feature then... I'll do that.

**Comment by revolter** [comment]
So, is it done? How to update Alcatraz itself?
