### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by neonichu** [supermarin/Alcatraz#117]
Many cases of plugins failing to install are currently pretty much silent except for reading /var/log/system.log, also there can be follow-up errors making even that confusing because things like exit codes of xcodebuild, etc. are not checked. Would be cool to bubble issues up the user, similar to the notification when a plugin was successfully installed.

**Comment by supermarin** [comment]
@neonichu will be tackled in binary installer. if that ships good, we'll disable client building completely. If we don't, we'll reopen this issue
