### ISSUE TITLE
Support for Xcode plugin bundles (.xcplugin rather than .xcodeproj)

### ISSUE THREAD

**Issue by bengotow** [supermarin/Alcatraz#121]
Hi there,

First off, thanks for creating Alcatraz. This thing is really slick. I'm the author of the Spark Inspector, a nifty little developer tool that comes with an Xcode plugin (sparkinspector.com/xcode_integration.html). 

I'd love to add the Spark Inspector's Xcode plugin to the Alcatraz package list. It'd allow our users to grab the plugin easily, keep it up to date, and most importantly manage it along with the rest of their Xcode customizations.

The problem is, our Xcode plugin is closed-source, and is distributed as a .xcplugin. I contribute code to the open-source community whenever I can, but the plugin is a major differentiator for the app and we're not looking to open source it.

I'd love if Alcatraz accepted plugin repositories containing an .xcplugin bundle rather than an .xcodeproj so we could add the Spark Inspector's plugin.

**Comment by supermarin** [comment]
Hey Ben, this is the very next thing we're tackling (and sorry it took forever).
I'll close the issue just because it's already tracked in the milestone.
