### ISSUE TITLE
AlcatrazSpec.m shouldn't load the .xcplugin

### ISSUE THREAD

**Issue by rhgills** [supermarin/Alcatraz#134]
A few problems can be caused by AlcatrazSpec.m loading the .xcplugin.

#### If Alcatraz isn't installed, tests will fail. 

Because the unit tests are in a seperate project, Alcatraz isn't installed as part of running tests. After cloning the repo, the AlcatrazSpec.m tests wil fail until you install Alcatraz. Notably, the CI build does NOT appear to install Alcatraz. If I'm not mistaken, that means the CI build is relying on the Alcatraz.xcplugin already being installed on the machine it is running on (which might change at any time).

#### If Alcatraz is installed, multiple implementations of the same class conflict

Lots of messages like this when running tests:

"objc[5482]: Class ATZSegmentedCell is implemented in both /Users/rhgill/Library/Developer/Xcode/DerivedData/TestProject-gbwjeldyqmdkmqajexatqurhibiz/Build/Products/Debug/TestProject.app/Contents/MacOS/TestProject and /Users/rhgill/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz. One of the two will be used. Which one is undefined."

Depending on which implementation is used, we might be testing an out of date class. If the .xcplugin implementation wins and we have changed the Alcatraz class, we won't be testing our changes; we'll be testing the old Alcatraz class in the .xcplugin.

It's good that the plugin bundle itself is exercised, but any tests doing that must be seperate from the unit tests which directly exercise Alcatraz classes.

I'd recommend modifying the AlcatrazSpec as it is to not load an external plugin (and instead instantiate an Alcatraz directly), while considering creating a seperate target to exercise loading the plugin.

**Comment by supermarin** [comment]
Closing this as a nonfix.
Will rewrite tests with the new core.
