### ISSUE TITLE
Command Line Tools are available for installation...

### ISSUE THREAD

**Issue by crmitchelmore** [supermarin/Alcatraz#137]
Had trouble getting Alcatraz to show with "Command Line Tools are available for installation in the Downloads section of Preferences."

 I gave up twice before looking a little deeper.

Traced it back to:
```[NSTask launchedTaskWithLaunchPath:@"/usr/bin/git" arguments:@[@"--version"]];```

My local git install was at /usr/local/bin/git so this was throwing an error. Not sure if this is just a problem for me or others will come across it.

Managed to resolve with
```sudo ln -s /usr/local/bin/git /usr/bin/git```

**Comment by supermarin** [comment]
Closing the issue as this will be obsolete with binary distribution

**Comment by jayceekay** [comment]
just in case anyone finds this for future reference who has the latest git installed via homebrew, this is what worked for me:
```$ which git
/usr/local/bin/git
$ ls -la /usr/local/bin/git
/usr/local/bin/git@ -> ../Cellar/git/2.5.0/bin/git
$ sudo ln -s /usr/local/bin/git /usr/bin/git```
