### ISSUE TITLE
Suggest best practices for menu items

### ISSUE THREAD

**Issue by fabiopelosin** [supermarin/Alcatraz#153]
Currently plugins author add menu entries to the the menus that they consider more appropriate. Although this approach is reasonable it has some important limitations:

- Decreases discoverability.
- Creates confusion about which menu entries were are added by plugins.
- Is is difficult to have an overview of all the menu entries (and thus of the functionality) added by a plugin if it scatters its entries in different menus.

I'm proposing that Alcatraz should take the lead and provide a best practice. My suggestion is to identify a menu item which could host all the plugins (a dedicated one in the status bar named `Plugins` could be a good solution) and then plugins should add menu items named exactly after the plugin where they can group their entries.

**Comment by supermarin** [comment]
@kattrali we should put them up on alcatraz.io.

Closing this one as I'm bashing thru issues
