### ISSUE TITLE
It's really hard to see which packages are installed at a glance

### ISSUE THREAD

**Issue by Ahti** [supermarin/Alcatraz#166]
The current way of indicating wether a package is installed or not is, imho, pretty bad at doing what it's supposed to do: Give the user a quick way to see wether he has installed a specific extension.

This gif demonstrates my issue pretty well, I think:

![animated gif](http://f.cl.ly/items/3y2c1X0B0x2I1K2k2b1M/alcatraz-selected.gif)

With the animation, one can see the difference, but I think you will agree, that it is not a very obvious difference.

I would suggest adding a color-fill to the icon for installed packages (keeping the blue highlight color), to make it distinguishable more easily.

Alternatively, the color for uninstalled packages could be faded out even more, and for installed ones, a darker blue could be used.

**Comment by streeter** [comment]
I'd also recommend having a toggle to show only installed or uninstalled items.

**Comment by supermarin** [comment]
@streeter It's implemented as a part of  the redesign in `master`
