### ISSUE TITLE
Use popovers for screenshots

### ISSUE THREAD

**Issue by abbeycode** [supermarin/Alcatraz#181]
It would be a lot easier to preview many items if the eye button opened a popover, which is dismissed more easily than a custom HUD-style window, as is currently used.

It would be even better if the up/down arrow keys would cycle between the previews in the list once the popover was shown.

For an item that has no screenshot, perhaps it could use a webview to show the linked site with a URL at the bottom to open it in Safari.

I volunteer to implement this, if deemed a worthwhile change.

**Comment by supermarin** [comment]
The previews are now inline in master
