### ISSUE TITLE
Local plugins support and more features.

### ISSUE THREAD

**Issue by ExtremeMan** [supermarin/Alcatraz#194]
I was working for the last weeks on adding support of plugins that are saved on the developers machine rather then on github. It is required in cases when one is sharing plugins with others using private repository or any other way of distribution source codes.

Basic idea is that on the developers machine there is a folder with plugins that are not publicly available or are available publicly but aren't added to https://github.com/supermarin/alcatraz-packages for different reasons but these plugins are still managed by Alcatraz: installed, updated, removed and etc.

In order to bring that support I have to refactor Alcatraz a little bit (like moving all business logic out of VC) and also I have to add other features (like local user notification when new package is available, build package only if new version is available (based on version written in plist file), remove local build files, rebuild package only if new commits are available rather then each time pulling and building, inform user if installed package doesn't support current Xcode version, fix searching in plugin descriptions). Also I added several UI changes to support new features:
- switcher between Remote/Local packages
- "Installed" packages filter
- "New" packages filter.
Another useful feature is ability to tell Alcatraz which packages it should install automatically.

I have bunch of commits that I hope we could merge into main repo. All of them and final results could be found here https://github.com/ExtremeMan/Alcatraz/commits/sandbox.

Next issues are mostly resolved in the branch above: https://github.com/supermarin/Alcatraz/issues/178, https://github.com/supermarin/Alcatraz/issues/66, https://github.com/supermarin/Alcatraz/issues/73, https://github.com/supermarin/Alcatraz/issues/110, https://github.com/supermarin/Alcatraz/issues/143, https://github.com/supermarin/Alcatraz/issues/160, https://github.com/supermarin/Alcatraz/issues/166, https://github.com/supermarin/Alcatraz/issues/167.

Next issues could be easily resolved on top of my changes: https://github.com/supermarin/Alcatraz/issues/156.

**Comment by supermarin** [comment]
Feedback addressed in #187
