### ISSUE TITLE
xib file missing by installing from Alcatraz

### ISSUE THREAD

**Issue by onevcat** [supermarin/Alcatraz#196]
Hi,

Some users told me that the setting panel of my plugin [VVDocumenter](https://github.com/onevcat/VVDocumenter-Xcode) can not be opened on Xcode 6.0.1 and Xcode 6.1, if they install it by Alcatraz.

I just did a simple research on it and found the xib file is not correctly copied into the `Resources` folder of the xcplugin package, which caused the problem.

But everything works well if I build the plugin from Xcode myself. Do you have any clue about what happened? (Just test it on Xcode 5 again and the same situation now. I believe it works perfectly before.)

**Comment by orta** [comment]
fixed in #237

**Comment by jurre** [comment]
Thanks ^^
