### ISSUE TITLE
NSCompositeColor Unsupported in 10.9

### ISSUE THREAD

**Issue by kfmilitello** [supermarin/Alcatraz#207]
After downloading the project and attempting to compile, it seems that the project now requires OS X 10.10 due to NSCompositeColor within the ATZPreviewImageButton class. The documentation states this project is compatible with OS X 10.9 or later.

**Comment by supermarin** [comment]
@kfmilitello thanks for the report!

Did you install from `master`, or from `alcatraz.io`?

**Comment by kfmilitello** [comment]
master since I didn't have my proxy settings configured yet for curl on the
Mac I was using.

**Comment by jurre** [comment]
`master` is where our ongoing development happens, could you try building from the `deploy` branch and see if it also happens there?

**Comment by kfmilitello** [comment]
Sorry for the late response, deploy worked.

**Comment by supermarin** [comment]
Thanks @jurre @kfmilitello!

@kattrali maybe keep this open in case we want to support 10.9 in the next release?

**Comment by kattrali** [comment]
@supermarin Sounds good :+1:
