### ISSUE TITLE
Unable to install plugins

### ISSUE THREAD

**Issue by dexafree** [supermarin/Alcatraz#208]
Currently using XCode Version 6.2 (6C107a) (also tried in the last stable version).

Running Mavericks 10.9.5.

Reinstalled twice (uninstalled running the `rm -Rf` on the two folders shown at the README.md), and also rebooted twice.

I'm unable to install any plugin. The pie starts to load, but as soon as it gets to 33% of the pie, it goes back again.

If there is any way I can provide any more debug trace or something, please let me know

**Comment by jurre** [comment]
Could you try this:

1. Verify which copy (if more than one are installed) of git is being run (which git).
2. Make sure you're running a recent version of git (git --version).
3. If you've used Xcode developer preview releases in the past, make certain Xcode isn't stuck using an inappropriate developer path by resetting it (sudo xcode-select --reset).

**Comment by dexafree** [comment]
Solved it by running `sudo xcode-select --reset`

Thank you very much for your fast response :)

**Comment by jurre** [comment]
Great! ^^

**Comment by jakubdolejs** [comment]
I'm having the same problem. Plugins ostensibly start to install but only progress about a quarter way and then the button label reverts back to "Install".

I installed latest git (version 2.2.1), ran `sudo xcode-select --reset` but no luck. The only thing I can think of is that Alcatraz is using git that comes bundled with Xcode dev tools (mine is version 1.9.5). Any ideas? Thanks in advance.
