### ISSUE TITLE
Lin for Xcode 6

### ISSUE THREAD

**Issue by sascha** [supermarin/Alcatraz#210]
I've recently created a fork of [Lin](https://github.com/sascha/Lin-Xcode6) that supports Xcode 6 and Yosemite and contacted the original developer of Lin via GitHub and email weeks ago. Unfortunately I don't get a response from him and have numerous requests to submit my fork to Alcatraz. What's the procedure in this case? Should I just submit it using another name? I've removed backwards compatibility with Xcode 5 and pre-Yosemite, so replacing the current version of Lin with my fork is probably not a good idea.

**Comment by camina-apps** [comment]
+1

**Comment by werediver** [comment]
+1 Maybe bumping the version will work? Lets mark it 2.0 and keep 1.x as is.

**Comment by Hs-Yeah** [comment]
+1

**Comment by supermarin** [comment]
@sascha seems like the author of Lin doesn't want to maintain it anymore.
Commit: https://github.com/questbeat/Lin-Xcode5/commit/fac9db82716e39ea97ea775eba0a0f8b86c95951

You're welcome to get your Lin ready, and we'll replace the old one with your fork.

**Comment by questbeat** [comment]
Now it supports Xcode6. ([questbeat/Lin](https://github.com/questbeat/Lin))
Sorry for the inconvenience.

**Comment by jurre** [comment]
Awesome, thanks! ^^

**Comment by supermarin** [comment]
@questbeat thanks!

@sascha is there any outstanding work / PRs other than Xcode 6 support you'd want to get in?

**Comment by sascha** [comment]
@supermarin Not really. Only added some vibrancy for Yosemite but I don't mind if @questbeat doesn't add that. I'm going to close this issue..

**Comment by supermarin** [comment]
@sascha you're always welcome to open a pull-request for that on @questbeat's branch :+1:
