### ISSUE TITLE
Xcode 6.3 beta support

### ISSUE THREAD

**Issue by niyue** [supermarin/Alcatraz#213]
I used Xcode 6.1 previously with Alcatraz and it is working for me, but I found it stopped working in Xcode 6.3 beta. The "Package Manager" menu item does not appear in the "Window" menu.

I tried to run the install script again and restarted my Xcode 6.3 beta but it did not help. Any idea? Thanks.

**Comment by DoctorG** [comment]
I had the same problem.  Reset Xcode developer path and then uninstall Alctraz then reinstall.  

I followed the steps as outlined in the Readme and had success:  

Troubleshooting

If "nothing" happens when installing packages, try the following self-help steps:

Verify which copy (if more than one are installed) of git is being run (which git).
Make sure you're running a recent version of git (git --version).
If you've used Xcode developer preview releases in the past, make certain Xcode isn't stuck using an inappropriate developer path by resetting it (sudo xcode-select --reset).
 <https://github.com/supermarin/Alcatraz#uninstall>Uninstall

Open up your terminal and paste this: 

rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin
To remove all packages installed via Alcatraz, run rm -rf ~/Library/Application\ Support/Alcatraz/

**Comment by niyue** [comment]
@DoctorG I was not able to make it work even I followed the steps you said.

git info:
```
$ which git
/usr/bin/git
```

```
$ git --version
git version 1.9.3 (Apple Git-50)
```

Reset and remove everything:
```
sudo xcode-select --reset
rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin
rm -rf ~/Library/Application\ Support/Alcatraz/
```

Reinstall:
```
$ curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   391    0   391    0     0    249      0 --:--:--  0:00:01 --:--:--   249
  0 86023    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0x Alcatraz.xcplugin/
x Alcatraz.xcplugin/Contents/
x Alcatraz.xcplugin/Contents/Info.plist
x Alcatraz.xcplugin/Contents/MacOS/
x Alcatraz.xcplugin/Contents/Resources/
x Alcatraz.xcplugin/Contents/Resources/en.lproj/
x Alcatraz.xcplugin/Contents/Resources/eye_icon.tiff
x Alcatraz.xcplugin/Contents/Resources/link_icon.tiff
x Alcatraz.xcplugin/Contents/Resources/PluginWindow.nib
x Alcatraz.xcplugin/Contents/Resources/toolbar_colors.tiff
x Alcatraz.xcplugin/Contents/Resources/toolbar_plugins.tiff
x Alcatraz.xcplugin/Contents/Resources/toolbar_templates.tiff
x Alcatraz.xcplugin/Contents/Resources/en.lproj/InfoPlist.strings
x Alcatraz.xcplugin/Contents/Resources/en.lproj/Localizable.strings
100 86023  100 86023    0     0  21494      0  0:00:04  0:00:04 --:--:-- 42990

Alcatraz successfuly installed!!1!🍻   Please restart your Xcode.
```

Restart Xcode 6.3 beta, still nothing under Window menu.

**Comment by jurre** [comment]
I don't think we've shipped 6.3 support yet, but if you build from master it should work.

**Comment by niyue** [comment]
@jurre Thanks. I tried to build from source and it did work for me (but XVim, one of my favourite plugin, is still broken for Xcode 6.3 beta :( )

**Comment by danyalaytekin** [comment]
Tested a few minutes ago.  This does now build from source, but it still doesn't install from the shell script.

**Comment by supermarin** [comment]
@danyalaytekin that seems right, `master` is not released yet

**Comment by mcplectrum** [comment]
If you use Alcatraz, you can manually add the UUID:  <string>992275C1-432A-4CF7-B659-D84ED6D42D3F</string> to the array <key>DVTPlugInCompatibilityUUIDs</key> in the file ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/Info.plist

**Comment by niyue** [comment]
@mcplectrum Thanks. I installed XVim from source using its master branch and it worked for me. It seems the latest XVim changes are not available via the package manager yet.

**Comment by cactis** [comment]
for Xcode Version 6.3 (6D532l), it's working to add 992275C1-432A-4CF7-B659-D84ED6D42D3F for array DVTPlugInCompatibilityUUIDs in ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/Info.plist

**Comment by johnboiles** [comment]
I can confirm this fix works with the Xcode 6.3 (6D570) that shipped today, except that you need to use the UUID for the latest version (Taken from Console.app):

        9F75337B-21B4-4ADC-B558-F9CADF7073A7

**Comment by nefarianblack** [comment]
+1 @johnboiles solution

**Comment by kaiky25** [comment]
@fuxx wrote an amazing snippet that adds a new UUID for all plugins within the plugins folder

```bash
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add <#XCODE_UUID#>
```

Using the latest Xcode 6.3 (6D570) that was released yesterday, the same snippet would turn out to be

```bash
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add 9F75337B-21B4-4ADC-B558-F9CADF7073A7
```

In case you're wondering how to find out the UUID of your current Xcode, here is the code snippet that does that

```bash
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID
```

**Comment by fuxx** [comment]
That "defaults read" from @kaiky25 is nice =) Combining with that command you could do the following with bash in the future. 

```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
```

**Comment by kaiky25** [comment]
Thanks again @fuxx for the amazing snippet! I'll turn it into a bash script just for the sake of having the plugins working fine in the near future :D

**Comment by Rusik** [comment]
Thanks @fuxx, it's working :)

**Comment by jeffaburt** [comment]
Thanks @fuxx! All of my plugins are back to working again :)

**Comment by zipme** [comment]
@fuxx 💚💜💚💜

**Comment by ryanhoo** [comment]
@fuxx I knew all these tricks, but none of them works. I am using Xcode Version 6.3.2 (6D2105). :sob:

**Comment by supermarin** [comment]
Locking this issue since these actions aren't supported by Apple.
