### ISSUE TITLE
Alcatraz on Xcode 6.2 crash

### ISSUE THREAD

**Issue by kingstal** [supermarin/Alcatraz#220]
I have just updated Xcode to 6.2, and download the Alcatraz repository from Github and build it in Xcode.
Alcatraz has already appeared in Xcode.
![new issue supermarin-alcatraz safari at 18 39 26](https://cloud.githubusercontent.com/assets/5668852/6573360/ec6211de-c754-11e4-9214-64474b5291c3.png)

The problem is when I touch the **Package Manager** Xcode crashed.
![xcode-crash](https://cloud.githubusercontent.com/assets/5668852/6573663/2f74b6a4-c758-11e4-8d1f-8ab6936aa44b.png)

I don't know how to fix it!

**Comment by imranali123** [comment]
same happened with me. Any luck?

**Comment by jurre** [comment]
So you built from master then? @kattrali

**Comment by imranali123** [comment]
Yes

**Comment by kattrali** [comment]
Very strange. Maybe try clean and build again? I'm not seeing anything unusual running the same version of Xcode (6C131e) using commit d9ac75dd9b9b1dc4235a44d128b56679773c4f2b.

**Comment by kingstal** [comment]
@kattrali , I have tried clean and build again.Everything is OK,thank you very much.

**Comment by kattrali** [comment]
Awesome! Glad to help!
