### ISSUE TITLE
A little problem with the picture in readme

### ISSUE THREAD

**Issue by dabing1022** [supermarin/Alcatraz#221]
I installed Alcatraz by `curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh`.

The picture showed in Readme is 

![](https://camo.githubusercontent.com/919efe4e1e53237df51d7010c862bd5c04fd6a70/687474703a2f2f616c63617472617a2e696f2f696d616765732f73637265656e73686f744032782e706e67)

But Mine is 

![](http://childhoodgamedev.qiniudn.com/question_QQ20150311-1.png)

What's wrong? The first one seems more friendly to preview the plug-ins.

**Comment by kattrali** [comment]
Please hold, we are in the middle of shipping the first one!!1!
