### ISSUE TITLE
Alcatraz is updating itself to an older version

### ISSUE THREAD

**Issue by luosheng** [supermarin/Alcatraz#224]
After installation, Alcatraz will try to update its own repository to the `deploy` branch, which is older than the current `master` branch and lacks the support for the latest Xcode 6.2 UDID. That's to say, Alcatraz will not function when Xcode restarts.

Maybe it should be “fixed” by bumping the version to 1.0.10 and merging the changes from `master` to `deploy`.

**Comment by TofPlay** [comment]
Same issue

**Comment by jurre** [comment]
We'll release a new version soon :)
