### ISSUE TITLE
why is the default behavior that this (or any) plugin will NOT work with a new version of xcode?

### ISSUE THREAD

**Issue by pvinis** [supermarin/Alcatraz#225]
we always need to add the new versions code manually. why is that? why not assume that is works?
if it works, then perfect. if it doesnt work, then it doesnt work anyway.
now, works or no, it doesnt work until we update the plist.

**Comment by jurre** [comment]
That's what apple has decided, it's just the way UUID compatibility works unfortunately.

It's something that [has been discussed](https://github.com/supermarin/Alcatraz/issues/122) a few times [before](https://github.com/supermarin/Alcatraz/issues/73), there has even been a [PR that added it](https://github.com/supermarin/Alcatraz/pull/120) and [here](https://github.com/supermarin/Alcatraz/pull/209). 

However, we feel auto updating the UUID kind of defeats the point of having them in the first place. It is up to plugin maintainers to make sure that their app works on the latest version of Xcode and update their UUID's accordingly.

We do however need to indicate wether or not a plugin will work.
