### ISSUE TITLE
Buttons highlighting is wierd

### ISSUE THREAD

**Issue by dev4dev** [supermarin/Alcatraz#226]
![screen shot 2015-03-11 at 21 11 11](https://cloud.githubusercontent.com/assets/722407/6604717/2ae1e3ce-c833-11e4-94d9-a52b2af466c8.png)

OSX 10.9.5

**Comment by supermarin** [comment]
What's weird?

**Comment by supermarin** [comment]
What's weird?

**Comment by supermarin** [comment]
What's weird?

**Comment by dev4dev** [comment]
So, that curvy strange shape is ok?
![screen shot 2015-03-11 at 23 36 07](https://cloud.githubusercontent.com/assets/722407/6607429/6af98d54-c847-11e4-9793-93229db4e266.png)
