### ISSUE TITLE
Rankings

### ISSUE THREAD

**Issue by esetnik** [supermarin/Alcatraz#229]
It would be nice to be able to sort plugins by number of downloads, rating, etc. I realize this would require a backend system to support but it would certainly add a lot of value.

I'm thinking something similar to npm.

**Comment by supermarin** [comment]
@esetnik we'll start with analytics and see how far we get / what can we learn from that.
Right now there's no plan of writing a separate backend app, because that'd be more fragile and require more maintenance.
