### ISSUE TITLE
Synchronizing installed plugins across multiple macs

### ISSUE THREAD

**Issue by cameronehrlich** [supermarin/Alcatraz#232]
I have my work computer and my home computer, and I would like to have my Alcatraz plugins stay the same for both Xcode installations.  Are there any good solutions to this out there that I am missing?

**Comment by mokagio** [comment]
As far as I know there's "Alcatraz" way yet. In the "road to 2.0" issue https://github.com/supermarin/Alcatraz/issues/201, there's a point to make a `alcatrazrc` file which would be what you're looking for.

One thing you could try is to have a git repo with your plugins and use it to keep stuff synced. **I never tried that though** and just thought about this option when reading your issue.

If you do go through the repo path please let us know how goes.

**Comment by mokagio** [comment]
(I do use a repo for my Xcode snippets and it works fine)

**Comment by cameronehrlich** [comment]
I may investigate implementing the .alcatrazrc file and/or the git method you are describing.  I'll report back.  If anyone else has any ideas, I would love to brainstorm on this.

**Comment by mokagio** [comment]
I'd love to see the `alcatrazrc` happen.

Let me know if I can help

**Comment by supermarin** [comment]
It's gonna be in 2.0. thanks for the patience :)
