### ISSUE TITLE
How to update script?

### ISSUE THREAD

**Issue by skywinder** [supermarin/Alcatraz#235]
Just want to request feature to show installed plugins and found, that new alcatraz version available.

Since there is not guides in readme - I just run uninstall script and then install script.

    rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin 
    && curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh

What the proper workflow to update plugin?

**Comment by jurre** [comment]
It happens automatically, you don't need to do anything

**Comment by skywinder** [comment]
As for me - it isn't. 
Just update manually recently as I described.

**Comment by edderrd** [comment]
same as me.

**Comment by kevin-hirsch** [comment]
Same as me.

**Comment by jurre** [comment]
Did you restart xcode?

**Comment by edderrd** [comment]
I did restart it, everything was gone needed to re-ran update script.

**Comment by jurre** [comment]
That's strange but it might have to do with the fact that we were a little behind in releasing a new version. Let me know if this happens again :/

**Comment by kevin-hirsch** [comment]
Same for me, restarted Xcode was not working. I had to re-install script. I was updating to Xcode 6.3.2 (6D2105). 
@jurre Could it be because I did the update of Xcode before you did add support for this version of Xcode?

**Comment by jurre** [comment]
Yes, it could be that indeed

**Comment by kevin-hirsch** [comment]
If I understand well, Alcatraz is begin auto-updated in my computer (when running from Xcode).
So, if I update Xcode too quickly, the plugin is unable to run due to non-compatibility and thus unable to auto-update itself.
Am I right?

And is there any workaround for this issue?

**Comment by supermarin** [comment]
Are you guys referring to updating Alcatraz itself, or the sub-plugins you've installed via Alcatraz?

The only problem currently is Alcatraz itself, you need to install it via script.
Once you have Alcatraz working in your Xcode, the child plugins will be updated on the fly.

**Comment by kevin-hirsch** [comment]
@supermarin I'm referring to Alcatraz itself. Once Alcatraz was updated, all my plugins were correctly updated as you said!

**Comment by skywinder** [comment]
@supermarin This issue is about Alcatraz auto-update. 
It doesn't update itself automatically, but as I understand - it should.

**Comment by supermarin** [comment]
@skywinder unfortunately it can't update itself, as it has to be loaded to do so

**Comment by skywinder** [comment]
As I can see from change my generated log: https://github.com/skywinder/Alcatraz/blob/add-change-log-file/CHANGELOG_AUTO.md (#234) - the last update was today (1.1.4) and it automatically updates as expected. so, probably this issue is outdated. 
![screen shot 2015-05-20 at 18 31 03](https://cloud.githubusercontent.com/assets/3356474/7729631/82595a98-ff1e-11e4-9262-792c14ad54bb.png)

**Comment by jurre** [comment]
You could also check the releases tab on github: https://github.com/supermarin/Alcatraz/releases
