### ISSUE TITLE
Provide an API for Plugin settings

### ISSUE THREAD

**Issue by orta** [supermarin/Alcatraz#241]
Every plugin eventually create's their own individual settings. Given that Alcatraz is installed in basically everywhere, it could provide an API accepting a nib + target and put it in the Xcode preferences.

Ideally it would expand this window by a few pixels and add a "Plugins" item, with the same tab bar for any plugin that wants to host its own settings.

![screen shot 2015-03-19 at 9 44 22 am](http://cl.ly/image/0c1m182C0B0i/Screen%20Shot%202015-03-19%20at%2010.13.35%20AM.png)

**Comment by AliSoftware** [comment]
:+1:

Except that once the user selected this new "Plugins" item, I'd rather use:
* Maybe use that "Locations / Source Trees" kind of TabBar to list "Plugins" vs "Templates", etc
* Use a Master/Detail view to list the plugins on the left and their settings (provided by their own XIB, or a JSON describing such settings to expose) on the Detail view. This would allow an arbitrary long list of plugins

**Comment by orta** [comment]
( agree with @AliSoftware - update the screenshot, think Behaviors is a better example here :+1:  )

**Comment by supermarin** [comment]
As discussed in Slack, we should make a standalone OSS repo to provide this functionality, and decouple plugins from Alcatraz
