### ISSUE TITLE
Unable to install plugins with Alcatraz on Xcode 6.2

### ISSUE THREAD

**Issue by jakubdolejs** [supermarin/Alcatraz#245]
I'm having the same problem as described in #208. Plugins ostensibly start to install but only progress about a quarter way and then the button label reverts back to "Install".

I installed latest git (version 2.2.1), ran `sudo xcode-select --reset` but no luck. The only thing I can think of is that Alcatraz is using git that comes bundled with Xcode dev tools (mine is version 1.9.5). Any ideas? Thanks in advance.

PS I added this as a comment to the original ticket #208 but nobody responded, presumably because the ticket is marked as closed. Apologies for the double post.

**Comment by mskobe** [comment]
Same problem here, I don't know why. Please help! Thank you

**Comment by mskobe** [comment]
@jakubdolejs did you install codepilot 3 with your Xcode? My problem is Codepilot crashes everything. 
It causes xcodebuild this error:
```
CPCodePilotPlugin.m:23 +[CPCodePilotPlugin load]; CODE PILOT: CURRENT_XCODE_VERSION: 0 CURRENT_XCODE_REVISION: 0
** INTERNAL ERROR: Uncaught exception **
Exception: Error (1000) creating CGSWindow
```
I remove Codepilot then everything works perfectly now! (I remove Codepilot and after installing other plugins, reinstall it again)

**Comment by supermarin** [comment]
CodePilot was making problems many times before.
Not sure if we should remove it from the list again until we switch to binary distribution

**Comment by davidbarker** [comment]
It seems CodePilot was causing this issue on my machine too.
