### ISSUE TITLE
Some plugins not working

### ISSUE THREAD

**Issue by cytryn** [supermarin/Alcatraz#247]
I was using AdjustFontSize and Polychromatic and they stopped working for no apparent reason.

I tried reinstalling Alcatraz and also cleaning the packages folder but it didn't work.

PS: some plugins are still working like AllTargets.

**Comment by jurre** [comment]
Could it be that the new plugins are not supporting the latest Xcode version yet?

**Comment by cytryn** [comment]
I have a friend using xcode 6.2 and his plugins are working

**Comment by cytryn** [comment]
I have reinstalled XCode and default things went to normal...

after a reinstalled Alcatraz and Polychromatic things went weird again and even my Dusk Colors got messed up:

http://f.cl.ly/items/2M322o0S0L2P102S1G2g/Image%202015-05-06%20at%2011.19.07%20AM.png

**Comment by supermarin** [comment]
Not an Alcatraz bug
