### ISSUE TITLE
Does not alcatraz provide the latest version?

### ISSUE THREAD

**Issue by limbo-lab** [supermarin/Alcatraz#252]
Many plugins, [KSImageNamed-Xcode](https://github.com/ksuther/KSImageNamed-Xcode), [FuzzyAutocompletePlugin](https://github.com/FuzzyAutocomplete/FuzzyAutocompletePlugin), for example, do not work by installing through alcatraz, yet works by self building.

**Comment by supermarin** [comment]
@limbo-lab alcatraz should update plugins to it's latest every time you launch xcode
