### ISSUE TITLE
how do you update alcatraz without reinstalling?

### ISSUE THREAD

**Issue by jonasman** [supermarin/Alcatraz#256]
Is there a command line to update alcatraz or how do we do it?

It is not in the docs. 

Is reinstalling the only way?

**Comment by jurre** [comment]
It updates automatically, just restart your xcode :)

**Comment by jonasman** [comment]
maybe it should be mentioned in the readme.md?

**Comment by jonasman** [comment]
also mine didn't update automatically. i did restart Xcode.

**Comment by supermarin** [comment]
@jonasman if you've installed the new xcode, then alcatraz wasn't loaded at all and thus couldn't be updated.
It was our fault we didn't ship on time to allow graceful updates.
For 6.3, you'll need to reinstall it using the script from  alcatraz.io

**Comment by jonasman** [comment]
Roger

**Comment by jamiebullock** [comment]
Yeah... probably worth mentioning "how to upgrade" in the README...

**Comment by jurre** [comment]
@jamiebullock pull requests are very welcome! :)
