### ISSUE TITLE
Unable to install templates (Xcode 6.3)

### ISSUE THREAD

**Issue by staticdreams** [supermarin/Alcatraz#259]
I have  a bizzarre problem. I'm not able to install any package under "Templates" section.
Color schemes and plug-ins are installing without any issues, but as soon as I tap "Install" on a template it quickly goes about 1/3 of the way and than rolls back.

I read other threads with similar issues suggesting I might have outdated version of git or my Xcode is set to a wrong command line compiler.. None of this is my case. I have just one version of Xcode installed (``6.3 release`` from Appstore) and my git version is ``2.3.5``. Btw the same happened to me with Xcode ``6.2``. 

My guess is templates might be installed differently than plugins and Alcatraz probably don't have some rights on a certain folder where they might go. How can I verify that? And are there any ways (apart from re-installing Xcode) to remedy this?

Another issue I'm having (and this might be related to the proper rights issue) is that some of the plugins I install may or may not appear as custom menu items. Sometimes they are just there when I launch Xcode (as intended) and sometimes they are not...

Any help is appreciated

**Comment by jurre** [comment]
Could it be that those plugins simply don't support 6.3 yet?

**Comment by staticdreams** [comment]
@jurre I don't think so. As I mentioned in my original post the same issues appeared in Xcode 6.2
As for the templates - are they installed in the same folders as all the other plugins? E.g `` ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/`` ?

**Comment by jurre** [comment]
No there's a completely separate install process for those

**Comment by staticdreams** [comment]
Ok, I got it to work. 
It seems that my original suspicions about the folder permission were the origin of the issue.
Unlike with other folders my current user didn't have write permissions on the folders where Templates should go. Those are: 
``~Library/Developer/Xcode/Templates/``
``~Library/Developer/Xcode/Templates/File Templates/``
By adding myself with read/write permissions on these folders resolved the issue.

**Comment by jurre** [comment]
:+1: :+1:
