### ISSUE TITLE
Without network some packages cannot be used

### ISSUE THREAD

**Issue by tujinqiu** [supermarin/Alcatraz#265]
Without network some packages cannot be used, such as VVDocumenter and FuzzyAutocompletePlugin, Most of the time I have to shut down the network in company. If the network is connected, i can use the packages.

**Comment by jurre** [comment]
That seems like an issue with the plugins themselves then? Maybe you can open an issue on their respective repo's?

**Comment by dev4dev** [comment]
You are doing something wrong, they perfectly work without network. There is nothing related to internet in them.

**Comment by supermarin** [comment]
Closing as it doesn't sound like an Alcatraz issue
