### ISSUE TITLE
Xcode toolbar is gone crazy after the update

### ISSUE THREAD

**Issue by FUAdrian** [supermarin/Alcatraz#266]
Hello folks,

I need some help/advise. I'm using Xcode 6.3 (AppStore version) on my MacBook Air. I wanted to update Alcatraz trough the master, which worked fine, but no plugins seems to work. So I updated Alcatraz trough the terminal and all plugins seem to work again. But now I faced to a strange issue. The toolbar of Xcode is gone crazy. I can't customize it like you usually would do. Some buttons (like Play/Stop) are invisible and you can't drag them back from the customization view. I tried to restart my system and also fully reinstalled Xcode. Nothing helped me. 

Is there anything else I could try. This issue drives me crazy. :/

**Comment by jurre** [comment]
I doubt Alcatraz is causing this, could you try uninstalling/reinstalling plugins to figure out if any 3rd party plugin is causing this?

**Comment by FUAdrian** [comment]
Thx a lot, I don't know why I didn't try that on my self. I just removed all of them and Xcode is fine now. :)

**Comment by jurre** [comment]
No problem, if you do figure out which plugin it is please let me know in case anyone else asks about it

**Comment by FUAdrian** [comment]
It was "WindowFlex". Strange that the old Xcode 6.3 beta version had no issue with it.
