### ISSUE TITLE
Export plugin configuration

### ISSUE THREAD

**Issue by moyoteg** [supermarin/Alcatraz#268]
I would like to export my Alcatraz plugin configuration somehow to my other computers without having to manually install all the same plugins =).

If there is a way to do it please let me know!

Thanks!

**Comment by jurre** [comment]
Currently there isn't but this is on our roadmap! I'm going to close this issue to keep the backlog tidy for ourselves but please know we do plan on adding this.

**Comment by moyoteg** [comment]
No worries! Thanks!
