### ISSUE TITLE
Alcatraz doesn't work in Xcode 6.3.1

### ISSUE THREAD

**Issue by diegarc** [supermarin/Alcatraz#269]
I tried exiting Xcode and rerunning the install script, but it doesn't seem to help. It's no appearing in the Window menu. My Info.plist file already have the correct entry in the DVTPlugInCompatibilityUUIDs array. I tried everything I found on google but is not working.

**Comment by oa414** [comment]
I aslo have this problem

**Comment by nerakhon** [comment]
Same here

**Comment by supermarin** [comment]
Released in 1.1.3
