### ISSUE TITLE
Alcatraz doesn't work with Xcode 6.3.2

### ISSUE THREAD

**Issue by Prince2k3** [supermarin/Alcatraz#273]
Have you guys looked into getting Alcatraz to work the GM Build of Xcode 6.3.2 or update the install script to work with the version. I ran it many times and nothing seems to be working.

**Comment by aszabo-ovalet** [comment]
Waiting for this to work as well.

**Comment by peyotll** [comment]
+1 Could you release the version including 6.3.2 fix?
Great project by the way ;)

**Comment by saiday** [comment]
For whom that upgrade Xcode use this snippet to add `DVTPlugInCompatibilityUUID` to your Xcode plugins info plist
```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
```

**Comment by eagle-dan1349** [comment]
For some reasons, it does not work for me.
xcode notifies of unexpected bundles, but loading them gives no result.
Anything helpful?

**Comment by staticdreams** [comment]
I'm also experiencing issues. Automatic installation script doesn't seem to work with latest changes, so I compiled from ``.xcproject``. Package Manager won't show up in the menu. After @saiday command line Package Manager showed up, but clicking on it crashes Xcode..

**Comment by staticdreams** [comment]
Never mind. I see updated the installer package. It works fine now.

**Comment by priore** [comment]
i have fixed with this article [Alcatraz-Xcode6.3.2](http://pablin.org/2015/05/27/re-enable-alcatraz-on-xcode-6-dot-3-2-or-newer)
