### ISSUE TITLE
Alcatraz not showing up in 6.3.2

### ISSUE THREAD

**Issue by iamcam** [supermarin/Alcatraz#280]
Since updating to 6.3.2, even with an uninstall/reinstall, I cannot get Alcatraz's menu option to show up. Also, none of the plugins load

**Comment by vburojevic** [comment]
It opens menu for me, but plugins are not loaded in Xcode 6.3.2.

**Comment by niguang1024** [comment]
Me too, when I selected 'Skip Bundle'...

**Comment by wangjiebo** [comment]
And reinstall doesn't help.

**Comment by jkyin** [comment]
Me too, that's a really big problem.

**Comment by ddalkanat** [comment]
Me too

**Comment by nonstriater** [comment]
Me too :[

**Comment by jurre** [comment]
Could anyone provide some more info, like a stracktrace maybe?

**Comment by langyapojun** [comment]
this is run pro. show in the console,maybe good for help to fix it......(U •́ .̫ •̀ U)
2015-05-25 18:15:45.410 Xcode[34458:643853] XFunnyEditor Plugin loaded
objc[34458]: Class XCBuildConfiguration is implemented in both /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/Versions/A/DevToolsCore and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster. One of the two will be used. Which one is undefined.
2015-05-25 18:15:45.753 Xcode[34458:643853] +[MCLog load], env: YES
2015-05-25 18:15:45.753 Xcode[34458:643853] +[MCLog pluginDidLoad:], NSBundle </Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MCLog.xcplugin> (loaded)
objc[34458]: Class VWKProject is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin/Contents/MacOS/ObjectGraph and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin/Contents/MacOS/KSHObjcUML. One of the two will be used. Which one is undefined.
objc[34458]: Class VWKWorkspaceManager is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin/Contents/MacOS/ObjectGraph and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin/Contents/MacOS/KSHObjcUML. One of the two will be used. Which one is undefined.
objc[34458]: Class VWKRunOperation is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin/Contents/MacOS/ObjectGraph and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin/Contents/MacOS/KSHObjcUML. One of the two will be used. Which one is undefined.
objc[34458]: Class VWKShellHandler is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin/Contents/MacOS/ObjectGraph and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin/Contents/MacOS/KSHObjcUML. One of the two will be used. Which one is undefined.
objc[34458]: Class VWKDocumentationManager is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin/Contents/MacOS/ObjectGraph and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin/Contents/MacOS/KSHObjcUML. One of the two will be used. Which one is undefined.
objc[34458]: Class VWKXCodeConsole is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin/Contents/MacOS/ObjectGraph and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin/Contents/MacOS/KSHObjcUML. One of the two will be used. Which one is undefined.
objc[34458]: Class CCPWorkspaceManager is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin/Contents/MacOS/CocoaPods and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaControlsPlugin.xcplugin/Contents/MacOS/CocoaControlsPlugin. One of the two will be used. Which one is undefined.
objc[34458]: Class CCPProject is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin/Contents/MacOS/CocoaPods and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaControlsPlugin.xcplugin/Contents/MacOS/CocoaControlsPlugin. One of the two will be used. Which one is undefined.
objc[34458]: Class XCWorkspace is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCBuildSettings is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class MHXcodeDocumentNavigator is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCAbstractDefinition is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCClassDefinition is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCFileOperationQueue is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCFrameworkDefinition is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCGroup is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCKeyBuilder is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCProject is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCSourceFile is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCSourceFileDefinition is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCSubProjectDefinition is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCTarget is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
objc[34458]: Class XCXibDefinition is implemented in both /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Peckham.xcplugin/Contents/Frameworks/MHImportBuster.framework/Versions/A/MHImportBuster and /Users/Sidney/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Auto-Importer.xcplugin/Contents/MacOS/Auto-Importer. One of the two will be used. Which one is undefined.
2015-05-25 18:15:47.193 Xcode[34458:643853] <ACCodeSnippetGitDataStore: 0x600001027e40> (git@github.com:langyapojun/myCodeSnippets.git) dataStoreWillAdd
2015-05-25 18:15:47.258 Xcode[34458:643853] <ACCodeSnippetGitDataStore: 0x600001027e40> (git@github.com:langyapojun/myCodeSnippets.git) dataStoreDidAdd
objc[34458]: Class IDEBlockScrollView is implemented in both /Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Versions/A/IDEKit and /Applications/Xcode.app/Contents/PlugIns/IDEProductsUI.ideplugin/Contents/MacOS/IDEProductsUI. One of the two will be used. Which one is undefined.
2015-05-25 18:15:47.866 Xcode[34458:643893]  DeveloperPortal: Using pre-existing current store at URL (file:///Users/Sidney/Library/Developer/Xcode/DeveloperPortal%206.3.2.db).
2015-05-25 18:15:47.920 Xcode[34458:643853] [MT] iPhoneSimulator: SimVerifier returned: Error Domain=NSPOSIXErrorDomain Code=53 "Simulator verification failed." UserInfo=0x600002e6f600 {NSLocalizedFailureReason=A connection to the simulator verification service could not be established., NSLocalizedRecoverySuggestion=Ensure that Xcode.app is installed on a volume with ownership enabled., NSLocalizedDescription=Simulator verification failed.}

**Comment by ppeelen** [comment]
Running this command will show the question to load or skip the bundles, however... even that didn't help for me: 
`find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID``

**Comment by luke0x** [comment]
+1

**Comment by Aster0id** [comment]
＋1

**Comment by difujia** [comment]
+1, please help.

**Comment by xiaonan0527** [comment]
+1

**Comment by newobux** [comment]
+1 :(

**Comment by jkyin** [comment]
@Aster0id Good job man! It works.

**Comment by iamcam** [comment]
Removing and installing Alcatraz did nothing until I found this gem #281 ... it was added to the "skipped" list.... and even after removing the entry, it sill gets added

![screen shot 2015-05-27 at 3 25 01 pm](https://cloud.githubusercontent.com/assets/51949/7848904/d5f12e36-0484-11e5-84df-31ce7e38ec94.png)

Even manually moving the entry from skipped to allowed did not work - Alcatraz is added back to skipped

**Comment by iamcam** [comment]
And for the record, attempting to remove that plist entry, removing alcatraz, reinstalling alcatraz, adding the UUIDs, then re-opening Xcode does not fix it.

**Comment by iamcam** [comment]
... I'm able to get the Xcode dialog back to allow/deny the plugin by changing the bundle ID in the Alcatraz Info.plist file (part of the package in the plugins dir). I haven't found where the `com.mneorr.Alcatraz` string is stored on the system that it keeps getting regenerated in the `DVTPlugInManagerNonApplePlugIns...` plist entry.

**Comment by Sethathi** [comment]
+1

**Comment by adamwaite** [comment]
Yeah I think all of these issues are related to -> https://github.com/omz/Dash-Plugin-for-Xcode/issues/39

"The latest Xcode version (6.3.2) asks you at launch if you want to load plugin bundles.", I think I said no to this.

I don't know how to bring that dialogue back up to test.

**Comment by cspeer** [comment]
@adamwaite I brought the bundles dialog back by following (this answer)[http://stackoverflow.com/a/30367823]. Specifically I executed:
```find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add E969541F-E6F9-4D25-8158-72DC3545A6C```

However, Acatraz still won't show up again in the Windows menu :(

**Comment by luke0x** [comment]
I solved this by:

* Running the commands as described by http://stackoverflow.com/questions/30361228/why-are-my-xcode-plugins-such-as-clang-format-installed-with-alcatraz-no-longe

`find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add 9F75337B-21B4-4ADC-B558-F9CADF7073A7`

then

`defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`

* Uninstalling Alcatraz (but not deleting my plugins)

`rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin`

* Reinstalling Alcatraz

`curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/master/Scripts/install.sh | sh`

* Quitting + restarting XCode 3-4 times, saying "yes" each time it asks about loading plugins, etc.

**Comment by iamcam** [comment]
I started over - quit Xcode, removed the Alcatraz plugins, rebooted the machine, and re-ran @pbendersky 's branch install script from #282 . Xcode asks about the plugin, I answered appropriately and now it works.

I'm still not sure what was going on yesterday.

**Comment by adamwaite** [comment]
Ah yeah that fixed it. Thanks @iamcam  and @pbendersky.

To bring the dialogue back I did a `defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2 2> /dev/null` (from #282)  to make Xcode forget you said no to loading custom plug-ins. Saying yes this time brought Alcatraz back into the game.

I'd already done the stuff in @luke0x's comment previously, thanks.

**Comment by langyapojun** [comment]
awesome,it works!!! just in scripts/install.sh add :defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2 2> /dev/null
next,run：sh install.sh
then,you restart xcode,and choose load bundle.
you will see in window has Package Manage

**Comment by cspeer** [comment]
Owww yeah, now it works for me as well. Had to do all the stuff the people above me already mentioned, plus @adamwaite 's
```defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2 2> /dev/null````

Thanks a lot guys!!!

**Comment by thuai** [comment]
+1

**Comment by jiashuw** [comment]
`defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2 2> /dev/null` will do the trick.

**Comment by ferologics** [comment]
none of the above worked for me, can anyone post a single comprehensive guide? thx

**Comment by romanvbabenko** [comment]
+1

**Comment by takdol** [comment]
Thanks @luke0x and @adamwaite!!! Package Manager is now showing in Xcode!!!

**Comment by double051** [comment]
Trying this command. 
    defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2 2> /dev/null
Sounds a little scary to be nuking that meta-plugin from a new Xcode release.

**Comment by doublenian** [comment]
Thanks @double051 ,
<pre>defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2 2> /dev/null</pre>

and
<pre>rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin</pre>
<pre>rm -rf ~/Library/Application\ Support/Alcatraz</pre>

Then Restart Xcode ,And Choose "load bundle" ,work for me
