### ISSUE TITLE
crash with could not load the nibName: ATZPackageListTableCellView

### ISSUE THREAD

**Issue by sunbohong** [supermarin/Alcatraz#284]
2015-05-28 11:57:17.662 Xcode[2945:117853] [MT] DVTAssertions: UNCAUGHT EXCEPTION (NSInternalInconsistencyException): -[NSNib initWithNibNamed:bundle:] could not load the nibName: ATZPackageListTableCellView in bundle NSBundle </Users/sunbohong/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin> (loaded).
UserInfo: (null)
Hints: None
2015-05-28 11:57:17.888 Xcode[2945:117853] [MT] DVTAssertions: 
Backtrace:
  0  0x00007fff89d78024 __exceptionPreprocess (in CoreFoundation)
  1  0x00000001001e2bb4 DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2  0x00007fff8251076e objc_exception_throw (in libobjc.A.dylib)
  3  0x00007fff89d77eed +[NSException raise:format:] (in CoreFoundation)
  4  0x00007fff8e865e34 -[NSNib initWithNibNamed:bundle:] (in AppKit)
  5  0x000000010c880fa5 -[ATZPackageTableViewDelegate configureTableView:] at /Users/sunbohong/Downloads/Alcatraz-master/Alcatraz/Controllers/ATZPackageTableViewDelegate.m:56 (in Alcatraz)
  6  0x000000010c87b62d -[ATZPluginWindowController reloadTableView] at /Users/sunbohong/Downloads/Alcatraz-master/Alcatraz/Controllers/ATZPluginWindowController.m:170 (in Alcatraz)
  7  0x000000010c87ae55 __44-[ATZPluginWindowController reloadPackages:]_block_invoke at /Users/sunbohong/Downloads/Alcatraz-master/Alcatraz/Controllers/ATZPluginWindowController.m:137 (in Alcatraz)
  8  0x000000010c886bf6 __51-[ATZDownloader downloadPackageListWithCompletion:]_block_invoke_2 at /Users/sunbohong/Downloads/Alcatraz-master/Alcatraz/Helpers/ATZDownloader.m:51 (in Alcatraz)
  9  0x000000010c887320 -[ATZDownloader URLSession:downloadTask:didFinishDownloadingToURL:] at /Users/sunbohong/Downloads/Alcatraz-master/Alcatraz/Helpers/ATZDownloader.m:97 (in Alcatraz)
 10  0x00007fff8ffd7a68 __82-[NSURLSession delegate_downloadTask:didFinishDownloadingToURL:completionHandler:]_block_invoke (in CFNetwork)
 11  0x00007fff8553b7e8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ (in Foundation)
 12  0x00007fff8553b5b5 -[NSBlockOperation main] (in Foundation)
 13  0x00007fff8553aa6c -[__NSOperationInternal _start:] (in Foundation)
 14  0x00007fff8553a543 __NSOQSchedule_f (in Foundation)
 15  0x0000000102045d43 _dispatch_client_callout (in libdispatch.dylib)
 16  0x0000000102054d9f _dispatch_main_queue_callback_4CF (in libdispatch.dylib)
 17  0x00007fff89ccb3f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ (in CoreFoundation)
 18  0x00007fff89c8668f __CFRunLoopRun (in CoreFoundation)
 19  0x00007fff89c85bd8 CFRunLoopRunSpecific (in CoreFoundation)
 20  0x00007fff90a4556f RunCurrentEventLoopInMode (in HIToolbox)
 21  0x00007fff90a452ea ReceiveNextEventCommon (in HIToolbox)
 22  0x00007fff90a4512b _BlockUntilNextEventMatchingListInModeWithFilter (in HIToolbox)
 23  0x00007fff8e6f19bb _DPSNextEvent (in AppKit)
 24  0x00007fff8e6f0f68 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] (in AppKit)
 25  0x0000000100761aaa -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:] (in DVTKit)
 26  0x00007fff8e6e6bf3 -[NSApplication run] (in AppKit)
 27  0x00007fff8e663354 NSApplicationMain (in AppKit)
 28  0x00007fff842b45c9 start (in libdyld.dylib)
 29  0x0000000000000001

**Comment by ahanmal** [comment]
Same issue in Xcode 7 (7A120f).

**Comment by supermarin** [comment]
Have you tried reinstalling from `alcatraz.io`?

**Comment by supermarin** [comment]
Closing as there's no input. Try removing the Alcatraz manually and reinstalling from the website.
