### ISSUE TITLE
Xcode 7.0 support

### ISSUE THREAD

**Issue by peyotll** [supermarin/Alcatraz#292]
Hi! Is there a way to quickly make it works on Xcode 7.0?

**Comment by jurre** [comment]
Yes, please try building from master :)

**Comment by peyotll** [comment]
I should have tried before asking... Thanks! :+1:

**Comment by jshier** [comment]
@jurre Just installed for Xcode 7 on El Capitan, didn't see it at launch. Console log said I need the UUID AABB7188-E14E-4433-AD3B-5CD791EAD9A3. Added and now it works, though I did get one crash: 
```
UNCAUGHT EXCEPTION (NSInternalInconsistencyException): -[NSNib initWithNibNamed:bundle:] could not load the nibName: ATZPackageListTableCellView in bundle NSBundle </Users/jshier/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin>
```
Quit Xcode, reinstalled, added UUID, and it seems to work now.

**Comment by drekka** [comment]
Hmm. Just tried it at home on my personal MBP and it worked fine. Will have to check the work MBP tomorrow.
