### ISSUE TITLE
Could not install Alcatraz on Xcode Version 6.4 (6E31c)

### ISSUE THREAD

**Issue by steffimueller** [supermarin/Alcatraz#294]
I tried: 

```
curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh
```
but there is no package manager menu after restart available.

**Comment by sainttail** [comment]
Same problem here

**Comment by confile** [comment]
I have the same porblem

**Comment by intonarumori** [comment]
+1

**Comment by gillesguilleminpiksel** [comment]
This is also true (unsurprisingly) for Xcode 7 Beta 1.

**Comment by lisi1987** [comment]
XCode 6.3.2(6D2105) +1

I tried running script 3 times and problem still exist

I'm run this script before reinstall  `Alcatraz`
```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add $UUID
```

**Comment by YangEdward** [comment]
+1

**Comment by priore** [comment]
+1 for Xcode 6.3.2

**Comment by steffimueller** [comment]
+1

**Comment by alkozin** [comment]
Maybe my app helps you? https://github.com/supermarin/Alcatraz/issues/276#issuecomment-113481130

**Comment by confile** [comment]
@alkozin Great but I still have this issue: https://github.com/supermarin/Alcatraz/issues/299

**Comment by imaks** [comment]
Same issue here, Alcatraz package manager menu not showing, however, I installed other plugins manually and they work in Xcode 6.4 (6E31c)

**Comment by Jaym3s** [comment]
+1

**Comment by derekjcarter** [comment]
+1 Xcode 6.4 (6E35b)

**Comment by julianvogels** [comment]
+1 Xcode 6.4 (6E35b)

**Comment by confile** [comment]
@supermarin Could you please comment on this issue. A lot of people seem to have problems here. Thanks.

**Comment by derekjcarter** [comment]
I could not ever get the shell script to work for me, but I did find a workaround.
```
1. open terminal
2. git clone the Alcatraz project
3. type:  defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID'
4. this will give you a UUID, so copy that
5. open the Alcatraz project
6. in the project settings (info tab), add another line to DVTPlugInCompatibilityUUIDs
7. paste in your uuid
8. build then close the project
9. restart xcode
10. you should be prompted with a load bundle or skip.. choose load bundle.
11. the plugin should work now
```

**Comment by arctouch-pedrocosta** [comment]
I can't install it on 6.4 6E35b anyone facing the same issue?

**Comment by stefangeir** [comment]
+1 Xcode 6.4 (6E35b) but @derekjcarter 's workaround worked for me.

**Comment by nlutsenko** [comment]
It's actually slightly easier than that.
No need even to download and build from source - just add the new 
`DVTPlugInCompatibilityUUID` (`7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90` - Xcode 6.4)
to 
`~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/Info.plist` under `DVTPlugInCompatibilityUUID` key.

**Comment by confile** [comment]
Still having this error: https://github.com/supermarin/Alcatraz/issues/310

**Comment by 80m** [comment]
@nlutsenko YAY!!!

for noobies:

open ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/Info.plist

add "7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90" to the DVTPlugInCompatibilityUUIDs array

restart xcode

you should see a box pop up that says something like "unexpected plugin: alcatraz"

**Comment by gwilliamspdx** [comment]
@supermarin There's no tagged release with these updates, so the install script detailed in the README doesn't install the version of the plugin with the necessary changes.

**Comment by kouky** [comment]
@80m thanks, that worked for me.

**Comment by difujia** [comment]
@80m 's approach works, thank you.
For a even **simpler and lazy** way, try this command after closing XCode:

    find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID` 

And restart XCode again, choose `Load Bundles`

**Comment by supermarin** [comment]
Alcatraz 1.1.6 is released with support for Xcode 6.4 and 7.0 beta.
Haven't confirmed 7.1.

**Comment by nlutsenko** [comment]
@supermarin Wait, will there be 7.1?
Did I miss something or you know something we dont? :smiley:

**Comment by supermarin** [comment]
@nlutsenko sorry, seems like I've misread the Xcode 7 Beta 1 comment from above.

**Comment by jacobvanorder** [comment]
If you are still running into issues, try resetting the plugin permissions as outlined [here](http://buegling.com/blog/2015/5/2/xcode-64-plugins-and-you).

**Comment by Blackjacx** [comment]
Thanks @80m this helped me to bring back the "Package Manager" menu in Xcode 7 (7A220)

**Comment by yangtaoNewGame** [comment]
xcode 7.1.1  can not  install any plugin.    is anyone have it ?
