### ISSUE TITLE
Xcode Command Line Tools are not currently installed, and are required to run Alcatraz.

### ISSUE THREAD

**Issue by confile** [supermarin/Alcatraz#299]
I installed Alcatraz on Xcode beta Version 6.4 (6E14).

When I try to open the package manager I get: 

![new_issue_ _supermarin_alcatraz](https://cloud.githubusercontent.com/assets/64265/8264620/a486ceac-16e8-11e5-9037-99b96ef57eea.png)

Commandline tool was installed with: ``xcode-select --install``

**Comment by supermarin** [comment]
I think you've installed cmd line tools for the main _Xcode.app_ installation,
and you're trying to run Alcatraz with Xcode beta.

You can confirm it with `xcode-select --print-path`.

**Comment by confile** [comment]
The result of ``/Library/Developer/CommandLineTools`` is: 

```
/Library/Developer/CommandLineTools
```

**Comment by confile** [comment]
What did I miss?

**Comment by kohtenko** [comment]
Same here. After updating `Command Line Tools` and `Xcode` from AppStore to 6.4 I get this message. 
Result of `xcode-select --print-path` is:
```
/Applications/Xcode.app/Contents/Developer
```

**Comment by richardshergold** [comment]
Exactly the same with me. After installing Command Line Tools and Alcatraz I get that message too (runing XCode 6.4). 

And running xcode-select --print-path I get:

/Applications/Xcode.app/Contents/Developer

Any idea what I should do ?

**Comment by confile** [comment]
With Xcode 6.4 running ``xcode-select --print-path`` I also get: 

```
/Applications/Xcode.app/Contents/Developer
```

**Comment by confile** [comment]
@supermarin Could you please take a look at this issue?
