### ISSUE TITLE
Just so you know: Crashes XCode 7 Beta

### ISSUE THREAD

**Issue by drekka** [supermarin/Alcatraz#301]
Just tried the latest master (22/6/2015). When building in XCode 7, it gives an error about not being able to run XCode. But the plugin is installed. So tried to run it and it crashed .XCode 7. Cleared old plugins directory and got same results.

**Comment by jshier** [comment]
Is it the same crash I mentioned in #292? If so, quitting Xcode and reinstalling Alcatraz worked for me.

**Comment by drekka** [comment]
1.1.6 seems to have fixed this.
