### ISSUE TITLE
XCode 7 Beta: Plugins will not install.

### ISSUE THREAD

**Issue by drekka** [supermarin/Alcatraz#302]
Just could be a factor of the various plugin's codebases, but none of the plugins will install. Each one starts the install progress bar, goes up to abut %30 progress. Stops then backs off back to 0%.

**Comment by akring** [comment]
Same problem,even the plugin support Xcode 7 already,such as VVDocumenter.I met this problem last year when Xcode 6 just released,so this will be fix soon I guess:)

**Comment by supermarin** [comment]
Have you tried with Alcatraz 1.1.6?

**Comment by drekka** [comment]
Alcatraz now appears to be working. The installs look a little slow, but that could just be my high expectations :-)

Thanks

**Comment by waynett** [comment]
same problem!! cannot install~

**Comment by JanXu-Dev** [comment]
I also encountered this situation.

**Comment by patxu** [comment]
Won't install either for Version 7.0 beta 4 (7A165t).

**Comment by drekka** [comment]
Last time the beta updated (b3) I had to run Alcatraz's update script. You can find it in the project root directory. This updates the UUIDs so it will work. But I admit I have not updated for Beta 4 yet so YMMV.

**Comment by palcalde** [comment]
I'm back with this problem in Xcode7 GM

**Comment by cerniuk** [comment]
Same problem.  Alcatraz installs fine but cannot install any plug-in (or plugin) using Alcatraz.

**Comment by Shahar2k5** [comment]
same here :+1:

**Comment by jsagorin** [comment]
I was installing VVDocumenter-XCode. [This]( https://github.com/onevcat/VVDocumenter-Xcode#xcode-version "Title") worked for me on Xcode 7.1. 
* Close Xcode
* From Terminal, run:

**defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1**
* Start Xcode. You'll be prompted to allow any bundles you've installed to load.

**Comment by cerniuk** [comment]
No joy with the defaults delete :-( Thanks tho for suggestion.

**Comment by LightMan** [comment]
I have the same problem, and is not about the loading process, because if I put other plugins in
/Users/<username>/Library/Application Support/Developer/Shared/Xcode/Plug-ins folder they are loaded and working properly. Alcatraz does not show in the menu.

**Comment by RMK19** [comment]
I have encountered the same, just like @drekka said.
Using Xcode 7.1. in OSX 10.10.5
