### ISSUE TITLE
Can't install plugins xCode 6.3.2

### ISSUE THREAD

**Issue by nikarc** [supermarin/Alcatraz#305]
When trying to install a plugin or templates, I click on the install button and nothing happens. Themes install correctly however.

**Comment by supermarin** [comment]
Could you please paste the output of `tail -f /var/log/system.log | grep -i xcode` when you try to install a plugin?

**Comment by nikarc** [comment]
Figured it out, it was already answered in issue #152 thanks to ardames and nextriot. I had to change my git path before building
