### ISSUE TITLE
Alcatraz crashes playground Xcode 6.4 

### ISSUE THREAD

**Issue by Prince2k3** [supermarin/Alcatraz#314]
Hello I'm constantly getting a crash when loading playground. I'm getting this error in the console with Alcatraz. 

com.apple.dt.Xcode.Playground[11801]: [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs

...

**Comment by jurre** [comment]
Could you try reinstalling alcatraz? It looks like it didn't update correctly

**Comment by daniyal-mirza** [comment]
I'm facing a similar issue as well. I've gotten the other plugins (downloaded through Alcatraz previously) up again. And they do seem to work so far, but launching Alcatraz's Package Manager still crashes Xcode.

**Comment by guillaume-algis** [comment]
@daniyal-mirza @Prince2k3 Do you have a crash report you could post here? Probably in Console.app.

**Comment by daniyal-mirza** [comment]
I'm only able to attach images here. Do you want me to copy the report here? Or link it here?

**Comment by guillaume-algis** [comment]
Something like pastebin or Github Gist should be fine :)

-- 
Guillaume

**Comment by daniyal-mirza** [comment]
This is a more recent version of the crash report. Crashes the moment I click Windows->Package Manager. http://pastebin.com/5zBBtYjT

**Comment by guillaume-algis** [comment]
Great, thanks! This seems to be the same crash as #284. I'll try to take a look tonight.

**Comment by daniyal-mirza** [comment]
Good Luck!

**Comment by guillaume-algis** [comment]
@daniyal-mirza Do you mind pasting the output of

    ls -lR ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin

here, please ?

**Comment by daniyal-mirza** [comment]
Here you go…

total 0
drwxr-xr-x  5 daniyalmirza  staff  170 Jul  7 21:19 Contents

/Users/daniyalmirza/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents:
total 8
-rw-------   1 daniyalmirza  staff  1327 Jul  7 21:19 Info.plist
drwxr-xr-x   3 daniyalmirza  staff   102 Jul  7 21:17 MacOS
drwxr-xr-x  17 daniyalmirza  staff   578 Jul  7 21:17 Resources

/Users/daniyalmirza/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS:
total 512
-rwxr-xr-x  1 daniyalmirza  staff  259004 Jul  7 21:17 Alcatraz

/Users/daniyalmirza/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/Resources:
total 328
-rw-r--r--  1 daniyalmirza  staff   8588 Jul  7 21:17 740-gear-selected.tiff
-rw-r--r--  1 daniyalmirza  staff   9668 Jul  7 21:17 740-gear.tiff
-rw-r--r--  1 daniyalmirza  staff   7730 Jul  7 21:17 808-documents-selected.tiff
-rw-r--r--  1 daniyalmirza  staff   7840 Jul  7 21:17 808-documents.tiff
-rw-r--r--  1 daniyalmirza  staff   8884 Jul  7 21:17 837-palette-selected.tiff
-rw-r--r--  1 daniyalmirza  staff   9614 Jul  7 21:17 837-palette.tiff
-rw-r--r--  1 daniyalmirza  staff  14720 Jul  7 21:17 bitbucket_grayscale.tiff
drwxr-xr-x  4 daniyalmirza  staff    136 Jul  7 21:17 en.lproj
-rw-r--r--  1 daniyalmirza  staff  12618 Jul  7 21:17 eye_icon.tiff
-rw-r--r--  1 daniyalmirza  staff  14698 Jul  7 21:17 git_grayscale.tiff
-rw-r--r--  1 daniyalmirza  staff  14280 Jul  7 21:17 github_grayscale.tiff
-rw-r--r--  1 daniyalmirza  staff   7680 Jul  7 21:17 link_icon.tiff
-rw-r--r--  1 daniyalmirza  staff   8680 Jul  7 21:17 toolbar_colors.tiff
-rw-r--r--  1 daniyalmirza  staff   7766 Jul  7 21:17 toolbar_plugins.tiff
-rw-r--r--  1 daniyalmirza  staff   7980 Jul  7 21:17 toolbar_templates.tiff

/Users/daniyalmirza/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/Resources/en.lproj:
total 16
-rw-r--r--  1 daniyalmirza  staff    92 Jul  7 21:17 InfoPlist.strings
-rw-r--r--  1 daniyalmirza  staff  1168 Jul  7 21:17 Localizable.strings

**Comment by guillaume-algis** [comment]
Thanks for the quick response.

Uh. Well that explains the crash. There should be 2 nibs in the Resources folder. I'll try to find out how they disappeared but that'll probably be tough.

**Comment by daniyal-mirza** [comment]
God Speed man!

**Comment by guillaume-algis** [comment]
@daniyal-mirza Well, I couldn't find the exact cause of the issue. But as @jurre suggested, I'd bet on a self-update gone wrong (but I couldn't find any real evidence supporting this theory).

A clean install of Alcatraz will most definitely fix it though.

    rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin
    curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/master/Scripts/install.sh | sh

Sorry I'm not more helpful :/

**Comment by daniyal-mirza** [comment]
It's ok. I did try the clean install previously, but no harm in trying again. Moreover, the plugins I really need are still installed from Xcode's previous iterations. So it isn't a showstopper for me.
Thanks anyways.

**Comment by daniyal-mirza** [comment]
P.S.: The clean install worked this time around. I'm a happy boy now! :+1:

**Comment by aerych** [comment]
> Well, I couldn't find the exact cause of the issue

If it helps at all, I encountered this after switching to a new laptop via OS X's Migration Assistant. A clean install worked as a fix for me as well.

**Comment by coffeewings** [comment]
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info.plist DVTPlugInCompatibilityUUID`

I run this code in terminal, then I build the ClangFormat plugin, 
the plugin works, I don't understand the meaning of it, I wish it is helpful for you
forgive my poor english
