### ISSUE TITLE
Alcatraz cannot be installed / used once Xcode Beta has been installed

### ISSUE THREAD

**Issue by JamieREvans** [supermarin/Alcatraz#316]
After installing the Xcode Beta, Alcatraz stops working for the non-beta version. Even following [@adin283's suggestion](https://github.com/supermarin/Alcatraz/issues/306#issuecomment-118523483), it won't fix the problem.

I've tried deleting the Beta and reinstalling everything, but Alcatraz is still nowhere to be seen.

**Comment by guillaume-algis** [comment]
Could you paste here the output of

     defaults read -app Xcode DVTPlugInManagerNonApplePlugIns-Xcode-$XCODE_VERSION

with `$XCODE_VERSION` replaced with the version of Xcode where Alcatraz does not show up, please?

eg.

    defaults read -app Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4.0

If you have multiple version of Xcode installed, please paste the output of this command for each Xcode version.

**Comment by adin283** [comment]
try the command below:
```
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID
{UUID}

find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add {UUID}
```

**Comment by JamieREvans** [comment]
ADIN! You're amazing. That works.

And thank you very much, @guillaume-algis. When I ran that command, it did say that it was skipping Alcatraz. Why is that? I've never skipped the "load bundles".

**Comment by jurre** [comment]
@JamieREvans this might be the default now in the new beta? :(

**Comment by JamieREvans** [comment]
@jurre The beta seems to be the cause. But this solution does solve the problem. I do have Xcode Beta uninstalled, now, though.

**Comment by richardshergold** [comment]
I have also uninstalled beta but have the same problem.

**Comment by jurre** [comment]
Yeah, once it writes those settings they are in effect, try running the commands above

**Comment by JamieREvans** [comment]
@richardshergold even after using @adin283's solution?

**Comment by richardshergold** [comment]
I'm getting:  Xcode Command Line Tools are not currently installed, and are required to run Alcatraz.

Command Line Tools are available for installation in the Downloads section of Preferences.

**Comment by richardshergold** [comment]
yes, I ran those two commands

**Comment by jurre** [comment]
Could you try `xcode-select -p` and make sure they are installed for the right Xcode version?

**Comment by richardshergold** [comment]
If I run that I get:

/Applications/Xcode.app/Contents/Developer

**Comment by jurre** [comment]
Could you try `xcode-select --install` just to make sure you actually have them installed?

**Comment by richardshergold** [comment]
Hi - did that - it says command line tools are already installed

**Comment by JamieREvans** [comment]
What's your output for `defaults read -app Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4.0`?

**Comment by richardshergold** [comment]
The domain/default pair of (/Users/richardshergold/Library/Preferences/com.apple.dt.Xcode, DVTPlugInManagerNonApplePlugIns-Xcode-6.4.0) does not exist

**Comment by guillaume-algis** [comment]
Try with

    defaults read -app Xcode DVTPlugInManagerNonApplePlugIns-Xcode-$(xcrun xcodebuild -version | head -n1 | awk '{ print $2 }')

**Comment by richardshergold** [comment]
that give me:

{
    allowed =     {
        "com.mneorr.Alcatraz" =         {
            version = 1;
        };
    };
    skipped =     {
    };
}

**Comment by guillaume-algis** [comment]
Did you do the latest command line tools update from the Mac App Store ?

**Comment by richardshergold** [comment]
I have no updates available in App Store so I guess so?

**Comment by JamieREvans** [comment]
Whats your Xcode version?

**Comment by richardshergold** [comment]
6.4 (6E35b)

**Comment by abunur** [comment]
Can you edit Swift 1.2 projects in Xcode 6.4 without getting Swift 2.0 error messages, after installing Xcode 7 beta?  I had that issue after installing beta 1, deleting the release version of Xcode and re-installing it fixed that for me.

Fuad Kamal
Anaara LLC
www.anaara.com
240.515.7578 (m)
214.279.1890 (f)
twitter: @flexRonin
behance: https://www.behance.net/fuadkamal
linkedIn: linkedin.com/in/anaara
photography: http://500px.com/fuad2

**Comment by jurre** [comment]
I don't see what that has to do with this issue?

**Comment by abunur** [comment]
my point was you might try re-installing Xcode (release version)

Fuad Kamal
Anaara LLC
www.anaara.com
240.515.7578 (m)
214.279.1890 (f)
twitter: @flexRonin
behance: https://www.behance.net/fuadkamal
linkedIn: linkedin.com/in/anaara
photography: http://500px.com/fuad2

**Comment by Buju77** [comment]
its also not working for me. Alcatraz is on the allowed list and xcode UUID is correctly added to the compatibility list. but i can't find Alcatraz menu anywhere. tried all the above steps but still doesn't help.

**Comment by guillaume-algis** [comment]
@Buju77 Can you paste the output of these commands here, please:

```
defaults read ~/Library/Preferences/com.apple.dt.Xcode.plist | grep DVTPlugInManagerNonApplePlugIns
defaults read ~/Library/Preferences/com.apple.dt.Xcode.plist | grep -B10 com.mneorr.Alcatraz

**Comment by Buju77** [comment]
```
➜  ~  defaults read ~/Library/Preferences/com.apple.dt.Xcode.plist | grep DVTPlugInManagerNonApplePlugIns
    "DVTPlugInManagerNonApplePlugIns-Xcode-6.3.2" =     {
    "DVTPlugInManagerNonApplePlugIns-Xcode-6.4" =     {
    "DVTPlugInManagerNonApplePlugIns-Xcode-7.0" =     {
➜  ~  defaults read ~/Library/Preferences/com.apple.dt.Xcode.plist | grep -B10 com.mneorr.Alcatraz
        allowed =         {
            "com.johnholdsworth.GitDiff" =             {
                version = "3.6";
            };
            "com.kitschpatrol.KPRunEverywhereXcodePlugin" =             {
                version = 1;
            };
            "com.luisfloreani.Auto-Importer" =             {
                version = 1;
            };
            "com.mneorr.Alcatraz" =             {
--
            };
            "com.kfinteractive.osx.dt.KFCocoaPodsPlugin" =             {
                version = 163;
            };
            "com.kitschpatrol.KPRunEverywhereXcodePlugin" =             {
                version = 1;
            };
            "com.luisfloreani.Auto-Importer" =             {
                version = 1;
            };
            "com.mneorr.Alcatraz" =             {
--
    "NSWindow Frame IDEManageContextSheet" = "2069 301 663 546 1440 -180 1920 1058 ";
    "NSWindow Frame IDEManageRunContextSheet" = "2016 407 768 454 1440 -180 1920 1057 ";
    "NSWindow Frame IDENewContextSheet" = "2154 717 493 144 1440 -180 1920 1057 ";
    "NSWindow Frame IDEOpenQuickly" = "345 424 1230 510 0 0 1920 1058 ";
    "NSWindow Frame IDEOrganizerWindow" = "3622 83 1440 769 3360 -180 1920 1057 ";
    "NSWindow Frame IDEPreferencesPanel" = "2025 237 750 501 1440 -180 1920 1057 ";
    "NSWindow Frame IDEReviewFilesWindow" = "1464 -91 1872 952 1440 -180 1920 1057 ";
    "NSWindow Frame NSColorPanel" = "3516 353 214 321 3360 -180 1920 1058 ";
    "NSWindow Frame NSFontPanel" = "1180 107 445 270 0 0 1920 1058 ";
    "NSWindow Frame Products" = "1527 -29 1200 788 1440 -180 1920 1057 ";
    "NSWindow Frame com.mneorr.Alcatraz.MainWindow" = "1578 -36 500 572 1440 -180 1920 1057 ";
➜  ~  
```

**Comment by guillaume-algis** [comment]
With which version of Xcode are you encountering the problem?

**Comment by Buju77** [comment]
Mac OS X 10.10.4 (14E46)
Version 6.4 (6E35b)

and I also have Xcode 7 beta 2 installed

**Comment by guillaume-algis** [comment]
Sorry @Buju77, I did not get the output I expected from the previous commands I asked you to run (`-B10` was not enough context). Would you be so kind as to run the following?

    defaults read -app Xcode | egrep '(DVTPlugInManagerNonApplePlugIns|allowed|skipped|com.mneorr.Alcatraz)'

Again, sorry for the hassle :/

**Comment by Buju77** [comment]
sry, did see your post afterwards ;)

```

**Comment by guillaume-algis** [comment]
Ok that's weird. Did you already try a clean install?

    rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin
    curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/deploy/Scripts/install.sh | sh

**Comment by Buju77** [comment]
yes, also tried that. still can't see the menu to open alcatraz

**Comment by stefangeir** [comment]
I have the same probem. Updated command line tools and did a clean install, still doesn't show up.

**Comment by Buju77** [comment]
Still doesn't work for me. But it seems that some plugins are loaded and some are not. eg. XCodeColors plugin is working fine but Alcatraz is not.

**Comment by cerniuk** [comment]
For those of us who want to know exactly what is going on and not have anything hidden behind command line parameters...  

Xcode comes out each time from Apple with a new UUID (Universally Unique Identifier). This UUID is used for the plug-in load to ensure that the plug-ins you have are disabled when you load a new Xcode.  Reading the tea leaves, this is Apple's way of making sure that their new Xcode is not blamed for any crashes cause by a plug-in, and to try to force plug-in makers to check for compatibility and release a new plug-in each time Xcode is released.  What this really ends up doing is forcing everyone through this goat rope of tweaking plug-ins that you really need to make Xcode tolerable. 

Wouldn't it be nice if Apple had the forethought to spend a little time to make a plug-in manager that we could use instead of wasting our team with this hokeypokey?  

Until Apple provides a way to manage plug-ins, here is a manual way for you to re-enable your plugins for any new version of Xcode (beta or otherwise). If you want to try and automate this with some command line interface scripting, have at it.

Assuming you are using TextWrangler (awesome tool) or similar....

1 - Copy the new DVTPlugInCompatibilityUUID tagged string from Xcode
1.1 - Open the plist from inside the App bundle (your path may differ, file is same) : /Applications/Development/Xcode/Xcode-beta.app/Contents/**Info.plist**
1.2 - search for "DVTPlugInCompatibilityUUID"
1.3 - copy the tagged string
Note: looks like (Xcode 8.0b1's): **<string>1637F4D5-0B27-416B-A78D-498965D64877</string>**
Note:  might be different if beyond Xcode 8.0b1

2 - Open your plug-ins folder
Note:  should be here: **~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins** 

3 - select a plugin

4 - Right click the plug-in file, select "**Show Package Contents**", Double-click "Contents" folder

5 - open the plug-in's **Info.plist**

6 - locate the 	**<key>DVTPlugInCompatibilityUUIDs</key>**

**7 - add copied string from step 1.3 to end of 	<key>DVTPlugInCompatibilityUUIDs</key> array**

8 Save the plug-in's Info.plist

9 Go to step three until you have edited each plugin

**Comment by borisyurkevich** [comment]
@cerniuk go and build your own IDE instead of insulting Xcode team 🔨

Plugins shouldn't work, trying to hack it means you compromise security of your own apps, putting your users at risk and putting at risk users trust to Apple.

**Comment by borisyurkevich** [comment]
@Buju77 why you don't even need Xcode colours if you can preview colors with Xcode 8?

**Comment by guillaume-algis** [comment]
@cerniuk @borisyurkevich this conversation has nothing to do with the original issue discussed here which is more than a year old.

If you want to discuss the plugin status in Xcode 8, please take it to https://github.com/alcatraz/Alcatraz/issues/475. Thanks.

**Comment by zinwalin** [comment]
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info.plist DVTPlugInCompatibilityUUID`
