### ISSUE TITLE
Install script URL on alcatraz.io should use the deploy branch

### ISSUE THREAD

**Issue by guillaume-algis** [supermarin/Alcatraz#322]
The install command on alcatraz.io currently uses the script on the `master` branch. I think it would be safer to use the branch `deploy` in case there is in the future a change in the install script on `master` incompatible with the current release on `deploy`.

So 

    curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/deploy/Scripts/install.sh | sh

instead of 

    curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/master/Scripts/install.sh | sh

Probably a job for @supermarin ;)

**Comment by supermarin** [comment]
Thanks for all your contributions @guillaume-algis !
I think this makes sense semantically, altho the install script never changes by humans.
It's automatically amended on `make release`.

**Comment by guillaume-algis** [comment]
I didn't realized the `github_release` target uploads the tarball directly on github, just after having updated the install URL. So I agree that it's a very minor issue, and there's very little chance it will cause any kind of problem in the future.

The change is totally up to you, it won't keep me awake at night :)

**Comment by supermarin** [comment]
Here you go Sir https://github.com/supermarin/Alcatraz/commit/8bdbb5b32fd1e4d2a21a8ad0b20dc16815ccc041

**Comment by guillaume-algis** [comment]
Thanks ^_^ !
I didn't realize the website source was available in this repo, I would have opened a PR otherwise haha.

**Comment by supermarin** [comment]
Yep, you can generate a website using `jekyll` on any repository you have, on a branch `gh-pages`.

Thanks for the contribution!
