### ISSUE TITLE
Document how to update an installed plugin

### ISSUE THREAD

**Issue by Arthaey** [supermarin/Alcatraz#326]
I've searched around for a description of how Alcatraz updates already-installed plugins, but I can't find anything. The code looks like it will update the *list* of available plugins straight from each project's master branch on github when the list loads, but that doesn't help for already-installed plugins, right?

**Comment by guillaume-algis** [comment]
All plugins are updated right after the list finishes loading.
If you want to force a plugin to update (shouldn't be necessary, but...) you can uninstall and reinstall it.

**Comment by Arthaey** [comment]
Ah, good to know! And thanks for the quick reply. Would you accept a pull request documenting that updates are automatic?

**Comment by Arthaey** [comment]
Ha, wait a minute, I *finally* saw where the docs *do* already say that. ;)
