### ISSUE TITLE
Can't install plugins with Xcode7 beta3

### ISSUE THREAD

**Issue by Xiaolong-Jin** [supermarin/Alcatraz#329]
I have tried to install VVDocument, however, the progress steps 1/4，then returns to the start point.

**Comment by patxu** [comment]
Same problem with all plugins. However, I can install color themes and templates without issues.

Xcode Version 7.0 beta 4 (7A165t)

**Comment by patxu** [comment]
same
Version 7.0 beta 4 (7A165t)

**Comment by jurre** [comment]
And alcatraz loads just fine? It might be an issue with the plugin then, they need to support the version themselves
