### ISSUE TITLE
Overwriting custom plugin

### ISSUE THREAD

**Issue by pwxn** [supermarin/Alcatraz#330]
I use a forked version of one of the plugins that is in the alcatraz list (with the same name). It seems that whenever I open xcode, the copy of the plugin I installed gets overwritten by the one alcatraz wants to use.

**Comment by jurre** [comment]
Hmm yes, you could maybe try renaming the manually installed plugin folder?

**Comment by pwxn** [comment]
Ah. That works. I had tried that yesterday, but was trying a bunch of other things at the same time, and so it must have conflicted with something else I was doing so it didn't seem to help.
