### ISSUE TITLE
The Xcode 6 can't see the package manage in window?

### ISSUE THREAD

**Issue by HelloWilliam** [supermarin/Alcatraz#331]
The Xcode 6 can't see the package manage in window?

**Comment by jurre** [comment]
Have you tried reinstalling Alcatraz?

**Comment by adrixpho** [comment]
I have the same issue, I reinstalled Alcatraz and nothing happened... Anyone knows if Alcatraz is not supported for xCode 6?

**Comment by supermarin** [comment]
It is supported. Please try searching the issues and reopen if you can't resolve.
