### ISSUE TITLE
Can't get Alcatraz to work with Xcode 6.4

### ISSUE THREAD

**Issue by Rayzworld** [supermarin/Alcatraz#336]
I have add 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 to DVTPlugInCompatibilityUUIDs of Alcatraz.xcplugin/Contents/Info.plist, then i restart xcode,  but it doesn't seem to help.

**Comment by ghousesgb** [comment]
same here :(

**Comment by ghousesgb** [comment]
Even tried this,
I could not get the shell script to work for me, but I did find a workaround.

1. open terminal
2. git clone the Alcatraz project
3. type:  defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID'
4. this will give you a UUID, so copy that
5. open the Alcatraz project
6. in the project settings (info tab), add another line to DVTPlugInCompatibilityUUIDs
7. paste in your uuid
8. build then close the project
9. restart xcode
10. you should be prompted with a load bundle or skip.. choose load bundle.
11. the plugin should work now

But LUCK...

**Comment by Rayzworld** [comment]
thx, it work now

**Comment by ghousesgb** [comment]
Yuppy, I have fixed the issue, 
This is what I have done.
In terminal type:
defaults read com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4
(check, alcatraz would be in blocklist (skipped))
Now, delete using following command
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-6.4
Restart your xcode....
