### ISSUE TITLE
Alcatraz not available in Xcode 7.1 beta

### ISSUE THREAD

**Issue by evermeer** [supermarin/Alcatraz#342]
Also none of the plugins are active.
Even after reinstallation of Alcatraz.

**Comment by alanhamlett** [comment]
Should be fixed with #343

**Comment by dev4dev** [comment]
@alanhamlett nope, that PR is about 7 GM, not about 7.1 beta

**Comment by jurre** [comment]
They don't have the same UDID?

**Comment by dev4dev** [comment]
nope
7.1 Beta `CC0D0F4F-05B3-431A-8F33-F84AFCB2C651`

**Comment by jurre** [comment]
I'll try to do a release soon: https://github.com/supermarin/Alcatraz/pull/346

**Comment by ronbarr** [comment]
Thanks for the branch - works great on 7.1

**Comment by jjhok** [comment]
is it works on xcode 7 GM (el capitan) ?

**Comment by jurre** [comment]
Yes, it should be available in both 7 and 7.1 now

**Comment by sajidhussain-honestbee** [comment]
Still not available

**Comment by dev4dev** [comment]
@sajidhussain-honestbee have you tried to reinstall it manually? everything works now

**Comment by sajidhussain-honestbee** [comment]
I tried using curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh 

The process went successful but nothing happened when I restarted the XCode.

**Comment by s3lvin** [comment]
I tried reinstalling and installing. Not working :(

**Comment by akshaynhegde** [comment]
Am also facing the same issue. I just updated to Xcode 7.1 and I reinstalled Alcatraz. And yet I don't see the "Package Manager" option under window.

**Comment by Chren** [comment]
The same to akshaynhegde.

**Comment by joshhaines** [comment]
Same here. Uninstalled Alcatraz first, then installed, but still not seeing Package Manager under Window. Can't seem to locate it anywhere.

**Comment by Rag0n** [comment]
@joshhaines Thank you. Have got the same problem and your solution works.

**Comment by caioremedio** [comment]
Nothing here seems to work for me. It's weird because on my Work mac its working fine, but at my Home mac nothing seems to make Alcatraz appear.

**Comment by alonecuzzo** [comment]
Not working for me either.  God I hate upgrading.

**Comment by mixo44** [comment]
+

**Comment by caioremedio** [comment]
Okay, I was building Alcatraz on Xcode without uninstalling it first. Just remove Alcatraz, download from Github, Run and restart Xcode. You should be fine now :)

**Comment by sajidhussain-honestbee** [comment]
The following did the magic for me:

https://github.com/supermarin/Alcatraz/issues/362#issuecomment-150457101

**Comment by juliaMarin** [comment]
I tried using curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh
successful message back but not "Package Manager".

Tried to install it through github didn't work either.

And the magic didn't work for me because i don't have DVTPlugInManagerNonApplePlugIns-Xcode-7.1

Any other ideas? Thanks a lot

**Comment by alvin777** [comment]
Same here: Xcode 7.1.1 doesn't show "Package Manager" menu item.

**Comment by esoto-gpsw** [comment]
I realize this post is for the Xcode Beta, but I see some recent posts.

In any case, I cloned the repo source and then built. It now works for me.

Steps:
1. Clone the repo to your mac.
2. Open the project in Xcode.
3. BUILD. It should build fine.
4. Restart Xcode. - you should now see "Package Manager" in the Window menu.

Perhaps there's been a change already in the source that has not yet made its way into the release archive.

**Comment by alanhamlett** [comment]
I've added an api endpoint with the latest Xcode releases updated daily:
https://wakatime.com/api/v1/xcode_releases

I'm sending myself an email with the dmg download link when any new Xcode version is released, to help with updating DVTPlugInCompatibilityUUID in plugins. If anyone else wants to get notified, send me an email alan@wakatime.com and I'll add you to the list.
