### ISSUE TITLE
Unable to install plug-ins on Xcode 7 GM

### ISSUE THREAD

**Issue by pronebird** [supermarin/Alcatraz#344]
What's left from past Xcode which is ok:

```
➜  Plug-ins  pwd
/Users/pronebird/Library/Application Support/Developer/Shared/Xcode/Plug-ins
➜  Plug-ins  ll
total 0
drwxr-xr-x  3 pronebird  staff   102B Sep 10 03:01 Alcatraz.xcplugin
drwxr-xr-x  3 pronebird  staff   102B Sep  8 11:46 KSImageNamed.xcplugin
drwxr-xr-x  3 pronebird  staff   102B Sep  8 11:01 SCXcodeEditorInset.xcplugin
drwxr-xr-x  3 pronebird  staff   102B Sep  8 11:05 VVDocumenter-Xcode.xcplugin
drwxr-xr-x  3 pronebird  staff   102B Aug  6 20:43 XCSnippetr.xcplugin
drwxr-xr-x  3 pronebird  staff   102B Sep  8 12:29 XcodeExplorer.xcplugin
```

Nothing happens when I hit install button for any of the plugins in Package Manager. I am able to remove existing plug-ins however. I keep my Xcode 7 GM in `/Applications/Xcode-gm.app` but that should not make any difference I believe.

**Comment by jurre** [comment]
Plugins will need to add support for the new xcode before you'll be able to install them, it usually takes a few days before most plugins have done this.

We're working on making this more clear in Alcatraz.
