### ISSUE TITLE
Automatically patch plug-ins to run on latest Xcode

### ISSUE THREAD

**Issue by pronebird** [supermarin/Alcatraz#347]
I have about 8 useful plug-ins installed and they all dead after Xcode upgrade. I have to open 8 issues or PRs on Github for each plug-in separately to have it working with my new Xcode.

Apparently this is a complete waste of time and each upgrade really discourages me from using Alcatraz and plug-ins.

And now when I removed some plug-in after upgrade and I am trying to reinstall it, I can't simply do this, the button flips from install to remove and back with no progress. Next time I open Xcode I don't remember what plug-in was that. At some point I stop keeping track of plug-ins that I had previously installed. 

I believe if Alcatraz could automatically deal with this problem, we would have much smoother transition between Xcode versions for plug-ins that don't mess much with Xcode guts. So maybe plug-in authors could opt-in or opt-out from auto patching via plist option.

**Comment by jurre** [comment]
We've had extensive discussions about this topic, please search the issue backlog for it. But the conclusion is that we don't want to support this in Alcatraz. Apple has put in place the UUIDs for a reason, it's to make sure that old plugins don't break new Xcode versions. If we would automatically patch any plugin without making sure we would bypass that. We feel it's up to plugin maintainers to ensure their plugins are compatible with new xcode versions.
