### ISSUE TITLE
Can't install any plugins in Xcode 7

### ISSUE THREAD

**Issue by michaeleiselsc** [supermarin/Alcatraz#351]
Whenever I click "Install" on a plugin it flashes "Installing" or something for an instant but then goes back to showing "Install", so I can't install anything.

**Comment by michaeleiselsc** [comment]
Never mind, it's because I had ran `sudo xcode-select --switch /Applications/Xcode-beta.app` a while back

**Comment by Shahar2k5** [comment]
i still have that issue. 
how did you fixed that?

Thanks.

**Comment by michaeleiselsc** [comment]
just xcode-select to the other xcode version

**Comment by Shahar2k5** [comment]
Thanks,

I already uninstalled everything and reinstall and it worked.

**Comment by yangtaoNewGame** [comment]
@michaeleiselsc  ,  why  you had  ran sudo xcode-select --switch /Applications/Xcode-beta.app ? do this will install plugin ???    I  can not believe??

**Comment by yangtaoNewGame** [comment]
@michaeleiselsc   my mac os only have one xcode ,the path is "/Applications/Xcode.app/Contents/Developer".  anyone know why alcatraz can't install any plugins in Xcode 7.1.1....   beg anyone could help me.

**Comment by jtdavid** [comment]
I'm with the same issue...

**Comment by ArunPrasanth-R** [comment]
Same issue

**Comment by guillaume-algis** [comment]
@ArunPrasanth-R Please open a new issue with a detailed description of what is happening and a dump of the relevant logs found in Console.app; that'd help identify the source of the problem. Thanks!
