### ISSUE TITLE
Not working on Xcode7 (7A220)

### ISSUE THREAD

**Issue by JohnnyTseng** [supermarin/Alcatraz#352]
Tried install with the script and build with Xcode7, the 「Package manager」item isn't showing on the 「Window」list on Xcode.

I've tried to add DVTPlugInCompatibilityUUID (0420B86A-AA43-4792-9ED0-6FE0F2B16A13) of Xcode7 in the Info.plist, and build again, it still doesn't work.

Anyone else?

**Comment by liujinlongxa** [comment]
i have the same problem

**Comment by chuckwong** [comment]
Me too//

**Comment by chuckwong** [comment]
I found the solution which may be helpful. Here's the link. http://xfwang.me/blog/2015/07/01/fix-Alcatraz-in-xcode64/
However, I've resolved it by delete all plugins and reinstall Alcatraz. I think the above solution might be much more helpful.

**Comment by rhyok** [comment]
Also experiencing this. Tried @chuckwong's solution, as well as reinstalling Alcatraz

@chuckwong: Just so you know, that command you linked just adds the DVTPlugInCompatibilityUUID for the current version of Xcode you have installed into every Xcode plugin that you have. Super useful command, but it's what the author had tried originally.

**Comment by XiaoRuiZuo** [comment]
Me too. have the same problem

**Comment by NathanLi** [comment]
So do I

**Comment by horseshoe7** [comment]
same problem!

**Comment by horseshoe7** [comment]
Based on this post, I just updated the version number: http://stackoverflow.com/a/30744531/421797

```defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.0```

**Comment by 0x686169** [comment]
same
Didn't see Package Manager in Window menu :(

**Comment by ForrestAlfred** [comment]
I confirmed that
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.0   
does work . 
I am using xcode 7  beta 7A121.

**Comment by welsonla** [comment]
@ForrestAlfred 
```ruby
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
```
then  
```ruby
sudo xcode-select --reset
```

**Comment by waniwang** [comment]
same problem

**Comment by ForrestAlfred** [comment]
Follow those we mentioned, you can solve it

**Comment by waniwang** [comment]
Thanks very much! Now it works!

**Comment by 0x686169** [comment]
Hi,
It's happen again on Version 7.0.1 (7A1001)

**Comment by ForrestAlfred** [comment]
I am using 7.0.1 now

**Comment by ForrestAlfred** [comment]
It works perfectly

**Comment by ForrestAlfred** [comment]
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID

sudo xcode-select --reset
Do this again

**Comment by 0x686169** [comment]
Thanks @ForrestAlfred ,
I try it again, again and again but I still cannot see Package manager in my Xcode's window menu.
Xcode Version 7.0.1 (7A1001)
Mac OS X EL Capitan

**Comment by ForrestAlfred** [comment]
As for me, I installed 70 bundles in Xcode7.0, then I opened 7.0.1,  it reminds of the bundles, then it works

**Comment by ForrestAlfred** [comment]
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.0

Then 

Sudo Xcode-select --reset

Maybe the command would be made some change like 

defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.0.1

**Comment by diogoguimaraes** [comment]
I'm on Xcode Version 7.0.1 (7A1001) and solved it by performing the following steps:
* Close Xcode
* If you have Alcatraz installed, uninstall it
* Perform as @ForrestAlfred posted before:
```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID

sudo xcode-select --reset
```
* Open Xcode
* Install Alcatraz
* Restart Xcode

**Comment by conanwhf** [comment]
Thanks for diogoguimaraes!
I have the same problem and try many things before, and now is OK.

**Comment by 0x686169** [comment]
thanks @diogoguimaraes , @ForrestAlfred 
It's works for me.

**Comment by Tuetuopay** [comment]
@ForrestAlfred THIS was the solution ! THANK YOU !
`defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.0`

**Comment by fabian-guerra** [comment]
I had this problem, but in my case, my work's mac user was not admin type, xcode install plugins only in administrator privileged users: 

`/Users/[adminuser]/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins`

I installed with admin privileges then worked fine.

**Comment by wuxulome** [comment]
thanks @diogoguimaraes 
It's works for me.

**Comment by shadowsyntax** [comment]
@diogoguimaraes Yeah it worked for me also.... appreciate

**Comment by xilin** [comment]
@diogoguimaraes It works. Thanks.

**Comment by trinhduc20** [comment]
Thanks @diogoguimaraes. It works now.

**Comment by ernestopino** [comment]
Thank you to @diogoguimaraes and @ForrestAlfred 
It's works for me and Xcode 7.1:

1. Close Xcode
2. Remove previous defaults for Xcode 7.0
<pre>defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.0
3. Uninstall Alcatraz
<pre>rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin
4. Remove all packages installed via Alcatraz
<pre>rm -rf ~/Library/Application\ Support/Alcatraz/
5. Perform as @ForrestAlfred posted before (changing Xcode version to "Xcode 7.1", this is my Xcode name app):
<pre>find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add defaults read /Applications/Xcode\ 7.1.app/Contents/Info DVTPlugInCompatibilityUUID
6. Reset Xcode select
<pre>sudo xcode-select --reset
7. Open Xcode
8. Install Alcatraz
<pre>curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh
9. Restart Xcode
10. Select "Load Bundles" in dialog box at Xcode start.

Goo luck and happy coding !!!

**Comment by hqman** [comment]
it works for me :)

**Comment by l3bel** [comment]
This works ! Thank you all, ernestopino for the numbered steps ;) no way to mi(e)ss

**Comment by Ataman11** [comment]
@diogoguimaraes steps worked for me. I guess the key for me was open xcode and only then install Alcatraz.

**Comment by fengyunjue** [comment]
thanks for @ernestopino .it works for me.  xcode7.1

**Comment by StevenMasini** [comment]
@ernestopino Doesn't works for me :(
But the first step tells me that:

```
| => defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.0
2015-11-04 10:51:25.621 defaults[13389:73382]
Domain (com.apple.dt.Xcode) not found.
Defaults have not been changed.
```

But I checked with the **defaults list** command and the domain **com.apple.dt.Xcode** is inside...
Nevertheless even after I followed the next steps, XCode 7.1 still doesn't want to load the plugin.

Any idea why the first step failed ?

**Comment by andy90s** [comment]
same problem

**Comment by andy90s** [comment]
@ernestopino    thank you !This works for me!

**Comment by slohr** [comment]
Alas, the steps listed by @ernestopino  do not work for me even though I'm on Xcode Version 7.1 (7B91b)

**Comment by smellflower** [comment]
@diogoguimaraes thks, your solution works for me.

**Comment by idiotlin** [comment]
@diogoguimaraes  The way doesn't work on Xcode 7.1.1(7B1005)

**Comment by syxc** [comment]
@ernestopino Thanks!
