### ISSUE TITLE
Xcode Command Line Tools are not currently installed

### ISSUE THREAD

**Issue by ZitingWei** [supermarin/Alcatraz#354]
When clicked Package Manager in Xcode, I got warning popped up like:
![2015-09-21 1 33 36](https://cloud.githubusercontent.com/assets/14345420/9987144/1f4f2666-6077-11e5-8ccd-b195fcd18243.png)

Details described at 
http://stackoverflow.com/questions/32689751/alcatraz-xcode-command-line-tools-are-not-currently-installed.

It was alright in Xcode 6.
Thanks for any advice!

**Comment by wlkfec** [comment]
same problem .. ( ▼-▼ )

**Comment by jurre** [comment]
Have you maybe switched Xcode versions or something?

**Comment by wlkfec** [comment]
Xcode6、Xcode7  . Can confirm that Command Line Tools has been installed successfully .

**Comment by ZitingWei** [comment]
Xcode 6 was alright with Alcatraz

**Comment by ZitingWei** [comment]
This answer solved my case: http://apple.stackexchange.com/questions/206715/alcatraz-xcode-command-line-tools-are-not-currently-installed/206767#206767
Looks like it's not Alcatraz's problem... but FYI and feel free to close this.

**Comment by jurre** [comment]
Thanks :)
