### ISSUE TITLE
Ability to show / filter only Swift Packages and templates 

### ISSUE THREAD

**Issue by kostiakoval** [supermarin/Alcatraz#356]
I want to see only templates and packed that are created or supported by Swift.

**Comment by jurre** [comment]
Pretty sure we're never going to do this so I'm just going to go ahead and close this. Sorry, not trying to be a jerk or anything, just want to keep the issue list clean.

**Comment by kostiakoval** [comment]
:+1: Sure, I understand. Thanks for taking your time and replying :)
