### ISSUE TITLE
Alcatraz is not working with Xcode 7.1

### ISSUE THREAD

**Issue by honghaoz** [supermarin/Alcatraz#359]

**Comment by honghaoz** [comment]
Got it worked

**Comment by Magnat12** [comment]
Have same problem. How do you make it work?

**Comment by honghaoz** [comment]
I moved `Alcatraz.xcplugin` outside from the plug-in folder. Opened Xcode, then quit. Later I moved back into the plug-in folder and reopened Xcode. 

It asked me whether to load bundles, just hit load and it loaded. 

However, actually, I did the same thing before but it crashed. Magical things happened..

**Comment by honghaoz** [comment]
@Magnat12

**Comment by jkyin** [comment]
@honghaoz You solved my problem, thank you.

**Comment by Domsware** [comment]
Don't work for me. Alcatraz load well but most of the plugins does not work.

**Comment by jurre** [comment]
Plugins need to add support for the new version themselves

**Comment by Domsware** [comment]
Ok, I've found a snippet to solve the problem:
```
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info.plist DVTPlugInCompatibilityUUID`
```
