### ISSUE TITLE
Xcode7.1 failure

### ISSUE THREAD

**Issue by biggercoffee** [supermarin/Alcatraz#362]
Xcode7.1 failure! thanks

**Comment by uptownboy** [comment]
Same here,deleted everyting and reinstalled, just can't find the manager under window menu.

**Comment by arctouch-pedrocosta** [comment]
same here :/ even after updating the plist file

**Comment by uptownboy** [comment]
problem fixed!!!!

run these 2 lines in terminal:
1:
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add defaults read /Applications/Xcode.app/Contents/Info.plist DVTPlugInCompatibilityUUID

2:
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1

3:
restart xcode!

**Comment by wzqcongcong** [comment]
Thanks! @uptownboy

**Comment by linjiansheng** [comment]
Thanks!

**Comment by zunware** [comment]
Oh, thanks. I was starting to freak out. :+1:

**Comment by biggercoffee** [comment]
ok , thanks

**Comment by biggercoffee** [comment]
@uptownboy  thanks

**Comment by johnwatsondev** [comment]
@uptownboy Thanks. 
But it doesn't need the step 1 in your approach. Just see #358

**Comment by BrightsCode** [comment]
thanks! It's work!

**Comment by maltsugar** [comment]
thanks! It's work!

**Comment by s1lence2012** [comment]
Thanks! I am doing this.

**Comment by dokun1** [comment]
all good now! I am still having a problem with KSImageNamed but everything else seems to be in working order.

**Comment by tudorturcanu** [comment]
Great, thanks! @uptownboy

**Comment by zvjerka24** [comment]
Great! It's working now (party)
Thanks! :+1:

**Comment by zhixing** [comment]
This works. Thanks for the advice!

**Comment by githotto** [comment]
Good work @uptownboy, you save my day/night !!
I finally got it working after upgrading to Xcode7.1 and removing the Xcode7.0.

**Comment by tianxiewuhua** [comment]
thanks @uptownboy ! it works now!

**Comment by xlsmearlx** [comment]
it worked! thx

**Comment by macecchi** [comment]
Thanks @uptownboy :+1:

**Comment by ArniDexian** [comment]
Thanks @uptownboy

**Comment by clangdiagnostic** [comment]
楼上＋1

**Comment by VectXi** [comment]
Thanks @uptownboy

**Comment by Ricardo1980** [comment]
Thanks!

**Comment by Oceanz** [comment]
Thanks!

**Comment by puvanarajan** [comment]
Thanks...

**Comment by VasantHugar** [comment]
Thanks @uptownboy

**Comment by xiaoMingChina** [comment]
Thanks @uptownboy

**Comment by Bionik6** [comment]
Thanks @uptownboy, it did work :+1:

**Comment by AndreasMaerki** [comment]
thanks!

**Comment by max-desiatov** [comment]
doesn't work with Xcode 7.1.1

**Comment by slohr** [comment]
Doesn't appear to work with this: Version 7.1 (7B91b)

**Comment by smellflower** [comment]
doesn't work with Xcode 7.1, i am not upgrade to Xcode 7.1, just install a new one completely.

**Comment by ouqiang** [comment]
Doesn't appear to work with this: Version 7.1 (7B91b)

**Comment by ben181231** [comment]
Xcode 7.1.1 Not Work

**Comment by smellflower** [comment]
the answers of this issue is worked for me.  especially thks  @diogoguimaraes and @ernestopino https://github.com/alcatraz/Alcatraz/issues/352

**Comment by Jiafan** [comment]
I'd executed commands below

1. clear something
```
rm -rf ~/Library/Application\ Support/Alcatraz/
rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add defaults read /Applications/Xcode\ 7.1.app/Contents/Info DVTPlugInCompatibilityUUID
sudo xcode-select --reset
```

2. open Xcode 

3. install Alcatraz

4. restart Xcode and I got the alert
<img width="532" alt="screen shot 2015-11-12 at 10 47 55 am" src="https://cloud.githubusercontent.com/assets/10692668/11109481/d92a1e60-892b-11e5-981b-1c6235f87fcd.png">

5. I selected load option but there is no manager under window option.

6. My operation system version is 10.11.1 and  Xcode version is 7.1.1

Thank you first.

**Comment by chinazyq** [comment]
Xcode 7.1.1, does not work.

**Comment by Antony138** [comment]
@Jiafan It work for me.  Xcoe7.1.1

**Comment by Jiafan** [comment]
@Antony138   Is there anything wrong with my steps ?

**Comment by Bardhued** [comment]
@Jiafan Xcode 7.1.1, does not work.

**Comment by superwave** [comment]
Xcode 7.1.1 doesn't work.
no package manager under the window tab, but plugins installed before works fine.

**Comment by fcy** [comment]
I've tried all the commands lines in all issues related to this and I can't make it work. The first run after clicking Load Bundles is weird, Xcode doesn't show my recent projects I have to restart it, then it comes back to normal. Neither time I have Package Manager under Window. Previous installed plugins still work.

**Comment by doubleday** [comment]
Same here. Tried everything. 

Deleted the 7.1.1 defaults and restarted. Actatraz should be there:

```
defaults read com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1.1
{
    allowed =     {
        "com.ihunter.Xcode-beginning-of-line" =         {
            version = 1;
        };
        "com.lixy.HighlightSelectedString" =         {
            version = 1;
        };
        "com.mneorr.Alcatraz" =         {
            version = 1;
        };
        "com.zenangst.MarvinPlugin" =         {
            version = "1.4.5";
        };
        "net.qfish.XAlign" =         {
            version = 1;
        };
    };
    skipped =     {
    };
}
```

But there's no Package Manager under Window

**Comment by sabiland** [comment]
Thx uptownboy! The same solution works also with Xcode 7.1.1.

**Comment by leo150** [comment]
UUID trick doesn't work. Xcode 7.1.1

**Comment by doubleday** [comment]
Ok seems to be this: #382

**Comment by chenqingxiao007** [comment]
My Xcode version is 7.1.1,but it doesn"t work

**Comment by jurre** [comment]
Have you tried reinstalling alcatraz?

**Comment by Jiafan** [comment]
@Bardhued @leo150 @chenqingxiao007  I'd made it. Thx @doubleday .Just clone branch master and built,then restart Xcode.

**Comment by chenqingxiao007** [comment]
ok,Let me try

**Comment by VictDog** [comment]
Its OK, problems has resolved

**Comment by chenqingxiao007** [comment]
ok.it can work.thanks
