### ISSUE TITLE
Still not working on Xcode 7.1 (7B91b)

### ISSUE THREAD

**Issue by dokun1** [supermarin/Alcatraz#366]
Installed Xcode 7.1.

Package Manager didn't show up. Followed instructions stemming from #361 by way of @diogoguimaraes and got Package Manager to show up in menu. I also deleted all cached data relating to the plugins before reinstalling.

Plugins not working as installed. For example, I installed VVDocumenter, restarted Xcode, no indication that anything was installed.

**Comment by jackyzh** [comment]
@dokun1 Take a look at https://github.com/supermarin/Alcatraz/issues/362#issuecomment-150457101

**Comment by dokun1** [comment]
thank you @jackyzh and @uptownboy!!!
