### ISSUE TITLE
Add more maintainers / turn into an org?

### ISSUE THREAD

**Issue by orta** [supermarin/Alcatraz#368]
Looking at the pull request list theres a lot of un-touched PRs that are sitting idle waiting with multiple requests from the authors with no replies from maintainers. I'm sure there are a lot of people wanting to help out in ensuring everything runs smoothly.

There are many good reasons for the current maintainers to be busy, perhaps encouraging more people to help run the project would be useful? I know I've been turned off contributing because of this, and I'd really like Alcatraz to succeed. 

This worked out really well on [Moya](http://cocoapods.org/pods/Moya) once we converted it to a [Moya org](https://github.com/moya), it's progressed a lot without our direct hand in the implementation.

**Comment by guillaume-algis** [comment]
> I'm sure there are a lot of people wanting to help out in ensuring everything runs smoothly.

✋

> I know I've been turned off contributing because of this, and I'd really like Alcatraz to succeed.

This. Some features are sorely needed (stand-alone app and binary distribution come to mind). I've been contemplating just running my own fork for some time now because the PR don't get feedback, but I'd much prefer avoiding fragmentation and help building an universal great solution for the community :) .

**Comment by sebastianludwig** [comment]
:+1:

**Comment by jurre** [comment]
I wouldn't be against this at all, it's up to @supermarin though IMO

**Comment by supermarin** [comment]
@guillaume-algis I owe you an email. for a longer time now, and I'm sorry it hasn't happened sooner.

**Comment by supermarin** [comment]
@orta I'm down for making an organization, and we already tried claiming https://github.com/alcatraz a year ago.
If you guys are willing to email Github and ask for the same thing, maybe they'd be open for reconsidering.

The main reason why most of the features didn't go in is that either code was not following our guidelines, or the features were half baked.
We always tried to keep it minimal and deal with as least maintenance as possible.

Let's revisit this within a week - I haven't had time for any OSS in awhile, but am getting back on track.

**Comment by orta** [comment]
The problem **is** things like this:

> @guillaume-algis I owe you an email. for a longer time now, and I'm sorry it hasn't happened sooner.

Which is exactly the kind of treatment I got for https://github.com/supermarin/Alcatraz/pull/154 - which was enough for me to stop contributing entirely. No offering of help along the way, just eventually "no, but thanks for the hours." "we'll cherry pick what we like".

> The main reason why most of the features didn't go in is that either code was not following our guidelines, or the features were half baked.

Doesn't explain why so many are just left abandoned and un-merged. Go read the PRs, there's a bunch of good ideas and abandoned after they did what the maintainers asked too.

> We always tried to keep it minimal and deal with as least maintenance as possible.

Low maintenance means no changes, which is fine, make this obvious on the README that Alcatraz is a done project. That's not a problem either.

In general though the maintainers attitudes has really held Alcatraz back, I've made annual "look into forking Alcatraz" notes in my calendar ( the last one I decided to skip because it looked like https://github.com/supermarin/Alcatraz/issues/201 might have been a mark of change ) but this time it really does feel like it's probably best to do a [merb](http://yehudakatz.com/2008/12/23/rails-and-merb-merge/) style fork with the aim of eventually bringing it back into alcatraz in year or so. I don't have time to run a full fork, as I have another [Mac app](https://github.com/cocoapods/cocoapods-app) to build but I would definitely contribute to someone elses.

**Comment by jurre** [comment]
Let's try to keep this on track:

I think it's probably a good idea to add more maintainers, it's clear that we haven't been able to put in the time that Alcatraz needs, I know I haven't.

If @supermarin and @kattrali feel the same way let's see if we can find the right people to help out.

**Comment by sebastianludwig** [comment]
In the meantime GitHub agreed to transfer the ownership of "alcatraz". I already forwarded @supermarin an email from GitHub staff.

**Comment by jurre** [comment]
:tada: thanks @sebastianludwig

**Comment by alanhamlett** [comment]
:+1: for an alcatraz org! Spread the work among many maintainers to take some load off you guys.

**Comment by damirstuhec** [comment]
+1

**Comment by supermarin** [comment]
@orta I'm happy to continue the conversation in a different tone than this.

Alcatraz has been a team work and writing stuff like above hits
everyone that has put their free time in it, not just me.

Every PR was reviewed by other team members, 
and would have been merged if others were comfortable with the contribution.

The organization is created, and we'll transfer the repo(s) this week.
Just moving Alcatraz to an organization will not solve this problems,
and we'll post about the next steps soon.

**Comment by orta** [comment]
Awesome :+1: - I'm excited to see what you come up with. 

I'm not trying to single you out @supermarin - and I'm totally grateful for the time you three have already put in, I'd like it to be possible for others to be able to also put the time in too.
