### ISSUE TITLE
Xcode corrupted when have installed Alcatraz

### ISSUE THREAD

**Issue by xtxwy** [supermarin/Alcatraz#370]
BackTrace:
Process:               Xcode [829]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               7.1 (9079)
Build Info:            IDEFrameworks-9079000000000000~8
App Item ID:           497799835
App External ID:       813804225
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [829]
User ID:               501

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
ProductBuildVersion: 7B91b
UNCAUGHT EXCEPTION (NSInternalInconsistencyException): -[NSNib _initWithNibNamed:bundle:options:] could not load the nibName: ATZPackageListTableCellView in bundle NSBundle </Users/netease/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin> (loaded).
UserInfo: (null)
Hints: None
Backtrace:
  0  0x00007fff8bd9dbba __exceptionPreprocess (in CoreFoundation)
  1  0x0000000106e77c7e DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2  0x00007fff9c5d34fa objc_exception_throw (in libobjc.A.dylib)
  3  0x00007fff8be043fd +[NSException raise:format:] (in CoreFoundation)
  4  0x00007fff958358b3 -[NSNib _initWithNibNamed:bundle:options:] (in AppKit)
  5  0x0000000119143ec9 -[ATZPackageTableViewDelegate configureTableView:] (in Alcatraz)
  6  0x0000000119140f78 -[ATZPluginWindowController reloadTableView] (in Alcatraz)
  7  0x0000000119140b0b __44-[ATZPluginWindowController reloadPackages:]_block_invoke (in Alcatraz)
  8  0x00000001191476f8 __51-[ATZDownloader downloadPackageListWithCompletion:]_block_invoke_2 (in Alcatraz)
  9  0x0000000119147b53 -[ATZDownloader URLSession:downloadTask:didFinishDownloadingToURL:] (in Alcatraz)
 10  0x00007fff99ffbcc2 __82-[NSURLSession delegate_downloadTask:didFinishDownloadingToURL:completionHandler:]_block_invoke (in CFNetwork)
......

**Comment by supermarin** [comment]
@xtxwy already fixed in a PR, should be released in the next update

**Comment by supermarin** [comment]
Please reopen if it's persistent in 1.1.12
