### ISSUE TITLE
EXC_BAD_ACCESS in starting Xcode when have installed Alcatraz

### ISSUE THREAD

**Issue by xtxwy** [supermarin/Alcatraz#373]
Process:               Xcode [9173]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               7.1 (9079)
Build Info:            IDEFrameworks-9079000000000000~8
App Item ID:           497799835
App External ID:       813804225
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [9173]

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x20:
--> 
    __TEXT                 0000000101719000-000000010171d000 [   16K] r-x/rwx SM=COW  /Applications/Xcode.app/Contents/MacOS/Xcode

Application Specific Information:
dyld: in dlopen()
ProductBuildVersion: 7B91b
/Users/netease/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz

Global Trace Buffer (reverse chronological seconds):
0.878314     CFNetwork                 	0x00007fff93b9cbf7 TCP Conn 0x7fd6ee204e70 started
0.980234     CFNetwork                 	0x00007fff93b6075e Creating default cookie storage with process/bundle identifier
0.980234     CFNetwork                 	0x00007fff93b606f6 Faulting in CFHTTPCookieStorage singleton
0.980234     CFNetwork                 	0x00007fff93b60585 Faulting in NSHTTPCookieStorage singleton
0.993966     CFNetwork                 	0x00007fff93c5e3b4 NSURLConnection finished with error - code -1100

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff9630e237 readClass(objc_class*, bool, bool) + 33
1   libobjc.A.dylib               	0x00007fff9630cbcf _read_images + 834
2   libobjc.A.dylib               	0x00007fff9630b8f9 map_images_nolock + 741
3   libobjc.A.dylib               	0x00007fff9630b54f map_2_images + 43
4   dyld                          	0x00007fff61a6382a dyld::notifyBatchPartial(dyld_image_states, bool, char const* (*)(dyld_image_states, unsigned int, dyld_image_info const*)) + 755
5   dyld                          	0x00007fff61a6d5fb ImageLoader::link(ImageLoader::LinkContext const&, bool, bool, bool, ImageLoader::RPathChain const&) + 231
6   dyld                          	0x00007fff61a63a12 dyld::link(ImageLoader*, bool, bool, ImageLoader::RPathChain const&) + 149
7   dyld                          	0x00007fff61a6b0af dlopen + 450
8   libdyld.dylib                 	0x00007fff90f7179c dlopen + 59
9   com.apple.CoreFoundation      	0x00007fff85a8c999 _CFBundleDlfcnLoadBundle + 153
10  com.apple.CoreFoundation      	0x00007fff85a8c818 _CFBundleLoadExecutableAndReturnError + 520
11  com.apple.Foundation          	0x00007fff9512f740 _NSBundleLoadCode + 512
12  com.apple.Foundation          	0x00007fff9512f118 -[NSBundle loadAndReturnError:] + 229
13  com.apple.Xcode.DevToolsCore  	0x000000010975a5fb __46-[XCPluginManager loadPluginBundle:forDomain:]_block_invoke + 50
14  com.apple.dt.DVTFoundation    	0x000000010194a9bc DVTInvokeWithFailureHint + 83
15  com.apple.Xcode.DevToolsCore  	0x000000010975a3c8 -[XCPluginManager loadPluginBundle:forDomain:] + 1054
16  com.apple.Xcode.DevToolsCore  	0x0000000109759e5b __46-[XCPluginManager findAndLoadPluginsInDomain:]_block_invoke + 621
17  com.apple.dt.DVTFoundation    	0x00000001019302c5 -[DVTPlugInManager _allowNonApplePlugInsFromDescriptors:error:] + 470
18  com.apple.dt.DVTFoundation    	0x000000010193054d -[DVTPlugInManager _checkNonApplePlugIns] + 239
19  com.apple.dt.DVTFoundation    	0x000000010193062e -[DVTPlugInManager initializePlugIns:] + 27
20  com.apple.dt.IDEFoundation    	0x000000010247c724 _IDEInitializeOtherPlugInStuff + 175
21  com.apple.dt.IDEFoundation    	0x000000010247d814 IDEInitialize + 3725
.......

**Comment by xtxwy** [comment]
Sorry for this issue. I found that I was fail to download Alcatraz. Please ignore this.

**Comment by jurre** [comment]
Thanks for letting us know :)
