### ISSUE TITLE
Ability to specify package repository for development

### ISSUE THREAD

**Issue by tvon** [supermarin/Alcatraz#66]
It could be convenient for contributors if there was a way to temporarily change the package repository URL so package changes could be tested before submitting a pull request to the main package repository.

I don't think this would need a UI, just allowing it to be changed via the command line (eg, defaults write) would be sufficient for contributors.

**Comment by beriberikix** [comment]
:+1:

**Comment by jurre** [comment]
This is actually on master now thanks to @kattrali!
