### ISSUE TITLE
Handling Xcode DVTPlugInCompatibilityUUIDs in future releases

### ISSUE THREAD

**Issue by tonyarnold** [supermarin/Alcatraz#73]
As raised in #72, this is going to be an issue in the long run. 

As it stands today, if the user updates Xcode to a newer release that changes it's `DVTPlugInCompatibilityUUID`, any plugins that do not contain the new UUID will be silently disabled when Xcode is launched.

The easiest way to restore this is to use a script to extract the new UUID:

```sh
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID
```

and then add it to the plugin:

```sh
defaults write MyPlugin.xcplugin/Contents/Info  DVTPlugInCompatibilityUUIDs -array-add $UUID
```

Initial thoughts are that it might be worth offering to install a LaunchDaemon or something similar that can offer to update all known instances of the Alcatraz plugin with the new UUID when it detects a new version of Xcode has been installed — but I'm not sure how I'd feel about having something like this sitting in the background on my mac.

Any other ideas?

**Comment by john0617** [comment]
有用

**Comment by jurre** [comment]
@john0617 ?
